// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file account.proto (package rockgame.account, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminResetUserPasswordRequest, AdminResetUserPasswordResponse, AdminUpdateUserStatusRequest, AdminUpdateUserStatusResponse, ChangePasswordRequest, ChangePasswordResponse, ConfirmPasswordResetRequest, ConfirmPasswordResetResponse, DeleteAccountRequest, DeleteAccountResponse, GetAssetsRequest, GetAssetsResponse, GetProfileRequest, GetProfileResponse, LoginRequest, LoginResponse, LogoutRequest, LogoutResponse, RefreshTokenRequest, RefreshTokenResponse, RegisterRequest, RegisterResponse, RequestPasswordResetRequest, RequestPasswordResetResponse, UpdateProfileRequest, UpdateProfileResponse, UploadAvatarRequest, UploadAvatarResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AccountService handles user authentication and profile operations.
 * Implemented by account-node.
 *
 * @generated from service rockgame.account.AccountService
 */
export const AccountService = {
  typeName: "rockgame.account.AccountService",
  methods: {
    /**
     * Register creates a new user account.
     *
     * @generated from rpc rockgame.account.AccountService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Login authenticates a user and returns tokens.
     *
     * @generated from rpc rockgame.account.AccountService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RefreshToken exchanges a refresh token for new access/refresh tokens.
     *
     * @generated from rpc rockgame.account.AccountService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Logout revokes the current session.
     *
     * @generated from rpc rockgame.account.AccountService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RequestPasswordReset sends a password reset link (if email exists).
     *
     * @generated from rpc rockgame.account.AccountService.RequestPasswordReset
     */
    requestPasswordReset: {
      name: "RequestPasswordReset",
      I: RequestPasswordResetRequest,
      O: RequestPasswordResetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ConfirmPasswordReset resets the password using a reset token.
     *
     * @generated from rpc rockgame.account.AccountService.ConfirmPasswordReset
     */
    confirmPasswordReset: {
      name: "ConfirmPasswordReset",
      I: ConfirmPasswordResetRequest,
      O: ConfirmPasswordResetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAssets returns the user's wallet balance.
     *
     * @generated from rpc rockgame.account.AccountService.GetAssets
     */
    getAssets: {
      name: "GetAssets",
      I: GetAssetsRequest,
      O: GetAssetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetProfile returns the user's profile information.
     *
     * @generated from rpc rockgame.account.AccountService.GetProfile
     */
    getProfile: {
      name: "GetProfile",
      I: GetProfileRequest,
      O: GetProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateProfile updates the user's profile (partial update).
     *
     * @generated from rpc rockgame.account.AccountService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ChangePassword changes the user's password.
     *
     * @generated from rpc rockgame.account.AccountService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: ChangePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteAccount soft-deletes the user account.
     *
     * @generated from rpc rockgame.account.AccountService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: DeleteAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UploadAvatar uploads a user avatar image.
     *
     * @generated from rpc rockgame.account.AccountService.UploadAvatar
     */
    uploadAvatar: {
      name: "UploadAvatar",
      I: UploadAvatarRequest,
      O: UploadAvatarResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Admin management RPCs — called by admin-node via gRPC.
     *
     * @generated from rpc rockgame.account.AccountService.AdminUpdateUserStatus
     */
    adminUpdateUserStatus: {
      name: "AdminUpdateUserStatus",
      I: AdminUpdateUserStatusRequest,
      O: AdminUpdateUserStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.account.AccountService.AdminResetUserPassword
     */
    adminResetUserPassword: {
      name: "AdminResetUserPassword",
      I: AdminResetUserPasswordRequest,
      O: AdminResetUserPasswordResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

