// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file activity.proto (package rockgame.activity, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivitiesResponse, ActivityStateResponse, CheckInConfigResponse, CheckInRequest, CheckInResponse, CheckInStateResponse, ClaimRechargeBonusRequest, ClaimRechargeBonusResponse, ClaimTimedGiftRequest, ClaimTimedGiftResponse, GetActivityStateRequest, GetCheckInConfigRequest, GetCheckInStateRequest, GetTimedGiftStatusRequest, GetWheelConfigRequest, GetWheelStateRequest, ListActivitiesRequest, SpinWheelRequest, SpinWheelResponse, TimedGiftStatusResponse, WheelConfigResponse, WheelStateResponse } from "./activity_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ActivityService handles check-in, lucky wheel, and promotional activities.
 * Implemented by activity-mesh.
 *
 * @generated from service rockgame.activity.ActivityService
 */
export const ActivityService = {
  typeName: "rockgame.activity.ActivityService",
  methods: {
    /**
     * ── Check-in ──
     *
     * @generated from rpc rockgame.activity.ActivityService.CheckIn
     */
    checkIn: {
      name: "CheckIn",
      I: CheckInRequest,
      O: CheckInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetCheckInState
     */
    getCheckInState: {
      name: "GetCheckInState",
      I: GetCheckInStateRequest,
      O: CheckInStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetCheckInConfig
     */
    getCheckInConfig: {
      name: "GetCheckInConfig",
      I: GetCheckInConfigRequest,
      O: CheckInConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Lucky Wheel ──
     *
     * @generated from rpc rockgame.activity.ActivityService.SpinWheel
     */
    spinWheel: {
      name: "SpinWheel",
      I: SpinWheelRequest,
      O: SpinWheelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetWheelState
     */
    getWheelState: {
      name: "GetWheelState",
      I: GetWheelStateRequest,
      O: WheelStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetWheelConfig
     */
    getWheelConfig: {
      name: "GetWheelConfig",
      I: GetWheelConfigRequest,
      O: WheelConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Activity list ──
     *
     * @generated from rpc rockgame.activity.ActivityService.ListActivities
     */
    listActivities: {
      name: "ListActivities",
      I: ListActivitiesRequest,
      O: ActivitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetActivityState
     */
    getActivityState: {
      name: "GetActivityState",
      I: GetActivityStateRequest,
      O: ActivityStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Recharge bonus + timed gift ──
     *
     * @generated from rpc rockgame.activity.ActivityService.ClaimRechargeBonus
     */
    claimRechargeBonus: {
      name: "ClaimRechargeBonus",
      I: ClaimRechargeBonusRequest,
      O: ClaimRechargeBonusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.ClaimTimedGift
     */
    claimTimedGift: {
      name: "ClaimTimedGift",
      I: ClaimTimedGiftRequest,
      O: ClaimTimedGiftResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.activity.ActivityService.GetTimedGiftStatus
     */
    getTimedGiftStatus: {
      name: "GetTimedGiftStatus",
      I: GetTimedGiftStatusRequest,
      O: TimedGiftStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

