// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file admin.proto (package rockgame.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ForwardRequest, ForwardResponse } from "./admin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AdminService is a generic gRPC service that wraps HTTP request/response.
 * Each backend service implements this to handle forwarded requests from Gate.
 * This avoids needing individual proto files for each backend service.
 *
 * @generated from service rockgame.admin.AdminService
 */
export const AdminService = {
  typeName: "rockgame.admin.AdminService",
  methods: {
    /**
     * @generated from rpc rockgame.admin.AdminService.Forward
     */
    forward: {
      name: "Forward",
      I: ForwardRequest,
      O: ForwardResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

