// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file admin.proto (package rockgame.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.admin.ForwardRequest
 */
export class ForwardRequest extends Message<ForwardRequest> {
  /**
   * @generated from field: string method = 1;
   */
  method = "";

  /**
   * @generated from field: string path = 2;
   */
  path = "";

  /**
   * @generated from field: map<string, string> headers = 3;
   */
  headers: { [key: string]: string } = {};

  /**
   * @generated from field: bytes body = 4;
   */
  body = new Uint8Array(0);

  /**
   * @generated from field: string query_string = 5;
   */
  queryString = "";

  /**
   * @generated from field: int64 user_id = 10;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: string device_id = 11;
   */
  deviceId = "";

  /**
   * @generated from field: string request_id = 12;
   */
  requestId = "";

  /**
   * @generated from field: string client_ip = 13;
   */
  clientIp = "";

  constructor(data?: PartialMessage<ForwardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.admin.ForwardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "headers", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 4, name: "body", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "query_string", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "device_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "client_ip", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ForwardRequest {
    return new ForwardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ForwardRequest {
    return new ForwardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ForwardRequest {
    return new ForwardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ForwardRequest | PlainMessage<ForwardRequest> | undefined, b: ForwardRequest | PlainMessage<ForwardRequest> | undefined): boolean {
    return proto3.util.equals(ForwardRequest, a, b);
  }
}

/**
 * @generated from message rockgame.admin.ForwardResponse
 */
export class ForwardResponse extends Message<ForwardResponse> {
  /**
   * @generated from field: int32 status_code = 1;
   */
  statusCode = 0;

  /**
   * @generated from field: map<string, string> headers = 2;
   */
  headers: { [key: string]: string } = {};

  /**
   * @generated from field: bytes body = 3;
   */
  body = new Uint8Array(0);

  constructor(data?: PartialMessage<ForwardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.admin.ForwardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "headers", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 3, name: "body", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ForwardResponse {
    return new ForwardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ForwardResponse {
    return new ForwardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ForwardResponse {
    return new ForwardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ForwardResponse | PlainMessage<ForwardResponse> | undefined, b: ForwardResponse | PlainMessage<ForwardResponse> | undefined): boolean {
    return proto3.util.equals(ForwardResponse, a, b);
  }
}

