// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file agent.proto (package rockgame.agent, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.agent.GetAgentInfoRequest
 */
export class GetAgentInfoRequest extends Message<GetAgentInfoRequest> {
  constructor(data?: PartialMessage<GetAgentInfoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.GetAgentInfoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAgentInfoRequest {
    return new GetAgentInfoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAgentInfoRequest {
    return new GetAgentInfoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAgentInfoRequest {
    return new GetAgentInfoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAgentInfoRequest | PlainMessage<GetAgentInfoRequest> | undefined, b: GetAgentInfoRequest | PlainMessage<GetAgentInfoRequest> | undefined): boolean {
    return proto3.util.equals(GetAgentInfoRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.AgentInfoResponse
 */
export class AgentInfoResponse extends Message<AgentInfoResponse> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: string agent_code = 2;
   */
  agentCode = "";

  /**
   * @generated from field: int32 level = 3;
   */
  level = 0;

  /**
   * @generated from field: int64 commission_rate = 4;
   */
  commissionRate = protoInt64.zero;

  /**
   * @generated from field: int64 total_commission = 5;
   */
  totalCommission = protoInt64.zero;

  constructor(data?: PartialMessage<AgentInfoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.AgentInfoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "agent_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "commission_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "total_commission", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AgentInfoResponse {
    return new AgentInfoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AgentInfoResponse {
    return new AgentInfoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AgentInfoResponse {
    return new AgentInfoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AgentInfoResponse | PlainMessage<AgentInfoResponse> | undefined, b: AgentInfoResponse | PlainMessage<AgentInfoResponse> | undefined): boolean {
    return proto3.util.equals(AgentInfoResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.GetSubordinatesRequest
 */
export class GetSubordinatesRequest extends Message<GetSubordinatesRequest> {
  constructor(data?: PartialMessage<GetSubordinatesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.GetSubordinatesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSubordinatesRequest {
    return new GetSubordinatesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSubordinatesRequest {
    return new GetSubordinatesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSubordinatesRequest {
    return new GetSubordinatesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSubordinatesRequest | PlainMessage<GetSubordinatesRequest> | undefined, b: GetSubordinatesRequest | PlainMessage<GetSubordinatesRequest> | undefined): boolean {
    return proto3.util.equals(GetSubordinatesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.Subordinate
 */
export class Subordinate extends Message<Subordinate> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname = "";

  /**
   * @generated from field: int64 total_recharge = 3;
   */
  totalRecharge = protoInt64.zero;

  /**
   * @generated from field: int64 total_commission = 4;
   */
  totalCommission = protoInt64.zero;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt = "";

  constructor(data?: PartialMessage<Subordinate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.Subordinate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "nickname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_recharge", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_commission", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Subordinate {
    return new Subordinate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Subordinate {
    return new Subordinate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Subordinate {
    return new Subordinate().fromJsonString(jsonString, options);
  }

  static equals(a: Subordinate | PlainMessage<Subordinate> | undefined, b: Subordinate | PlainMessage<Subordinate> | undefined): boolean {
    return proto3.util.equals(Subordinate, a, b);
  }
}

/**
 * @generated from message rockgame.agent.SubordinatesResponse
 */
export class SubordinatesResponse extends Message<SubordinatesResponse> {
  /**
   * @generated from field: repeated rockgame.agent.Subordinate subordinates = 1;
   */
  subordinates: Subordinate[] = [];

  constructor(data?: PartialMessage<SubordinatesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.SubordinatesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subordinates", kind: "message", T: Subordinate, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubordinatesResponse {
    return new SubordinatesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubordinatesResponse {
    return new SubordinatesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubordinatesResponse {
    return new SubordinatesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubordinatesResponse | PlainMessage<SubordinatesResponse> | undefined, b: SubordinatesResponse | PlainMessage<SubordinatesResponse> | undefined): boolean {
    return proto3.util.equals(SubordinatesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.GetCommissionsRequest
 */
export class GetCommissionsRequest extends Message<GetCommissionsRequest> {
  constructor(data?: PartialMessage<GetCommissionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.GetCommissionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCommissionsRequest {
    return new GetCommissionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCommissionsRequest {
    return new GetCommissionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCommissionsRequest {
    return new GetCommissionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCommissionsRequest | PlainMessage<GetCommissionsRequest> | undefined, b: GetCommissionsRequest | PlainMessage<GetCommissionsRequest> | undefined): boolean {
    return proto3.util.equals(GetCommissionsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CommissionRecord
 */
export class CommissionRecord extends Message<CommissionRecord> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: string source = 3;
   */
  source = "";

  /**
   * @generated from field: int32 status = 4;
   */
  status = 0;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt = "";

  constructor(data?: PartialMessage<CommissionRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CommissionRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommissionRecord {
    return new CommissionRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommissionRecord {
    return new CommissionRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommissionRecord {
    return new CommissionRecord().fromJsonString(jsonString, options);
  }

  static equals(a: CommissionRecord | PlainMessage<CommissionRecord> | undefined, b: CommissionRecord | PlainMessage<CommissionRecord> | undefined): boolean {
    return proto3.util.equals(CommissionRecord, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CommissionsResponse
 */
export class CommissionsResponse extends Message<CommissionsResponse> {
  /**
   * @generated from field: repeated rockgame.agent.CommissionRecord records = 1;
   */
  records: CommissionRecord[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  constructor(data?: PartialMessage<CommissionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CommissionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "records", kind: "message", T: CommissionRecord, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommissionsResponse {
    return new CommissionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommissionsResponse {
    return new CommissionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommissionsResponse {
    return new CommissionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CommissionsResponse | PlainMessage<CommissionsResponse> | undefined, b: CommissionsResponse | PlainMessage<CommissionsResponse> | undefined): boolean {
    return proto3.util.equals(CommissionsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.RequestSettlementRequest
 */
export class RequestSettlementRequest extends Message<RequestSettlementRequest> {
  /**
   * @generated from field: int64 amount = 1;
   */
  amount = protoInt64.zero;

  constructor(data?: PartialMessage<RequestSettlementRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.RequestSettlementRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestSettlementRequest {
    return new RequestSettlementRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestSettlementRequest {
    return new RequestSettlementRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestSettlementRequest {
    return new RequestSettlementRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequestSettlementRequest | PlainMessage<RequestSettlementRequest> | undefined, b: RequestSettlementRequest | PlainMessage<RequestSettlementRequest> | undefined): boolean {
    return proto3.util.equals(RequestSettlementRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.RequestSettlementResponse
 */
export class RequestSettlementResponse extends Message<RequestSettlementResponse> {
  /**
   * @generated from field: string order_no = 1;
   */
  orderNo = "";

  constructor(data?: PartialMessage<RequestSettlementResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.RequestSettlementResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_no", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestSettlementResponse {
    return new RequestSettlementResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestSettlementResponse {
    return new RequestSettlementResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestSettlementResponse {
    return new RequestSettlementResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RequestSettlementResponse | PlainMessage<RequestSettlementResponse> | undefined, b: RequestSettlementResponse | PlainMessage<RequestSettlementResponse> | undefined): boolean {
    return proto3.util.equals(RequestSettlementResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CreatePromoLinkRequest
 */
export class CreatePromoLinkRequest extends Message<CreatePromoLinkRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  constructor(data?: PartialMessage<CreatePromoLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CreatePromoLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePromoLinkRequest {
    return new CreatePromoLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePromoLinkRequest {
    return new CreatePromoLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePromoLinkRequest {
    return new CreatePromoLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePromoLinkRequest | PlainMessage<CreatePromoLinkRequest> | undefined, b: CreatePromoLinkRequest | PlainMessage<CreatePromoLinkRequest> | undefined): boolean {
    return proto3.util.equals(CreatePromoLinkRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CreatePromoLinkResponse
 */
export class CreatePromoLinkResponse extends Message<CreatePromoLinkResponse> {
  /**
   * @generated from field: string link = 1;
   */
  link = "";

  /**
   * @generated from field: string code = 2;
   */
  code = "";

  constructor(data?: PartialMessage<CreatePromoLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CreatePromoLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePromoLinkResponse {
    return new CreatePromoLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePromoLinkResponse {
    return new CreatePromoLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePromoLinkResponse {
    return new CreatePromoLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePromoLinkResponse | PlainMessage<CreatePromoLinkResponse> | undefined, b: CreatePromoLinkResponse | PlainMessage<CreatePromoLinkResponse> | undefined): boolean {
    return proto3.util.equals(CreatePromoLinkResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.GetAgentDashboardRequest
 */
export class GetAgentDashboardRequest extends Message<GetAgentDashboardRequest> {
  constructor(data?: PartialMessage<GetAgentDashboardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.GetAgentDashboardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAgentDashboardRequest {
    return new GetAgentDashboardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAgentDashboardRequest {
    return new GetAgentDashboardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAgentDashboardRequest {
    return new GetAgentDashboardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAgentDashboardRequest | PlainMessage<GetAgentDashboardRequest> | undefined, b: GetAgentDashboardRequest | PlainMessage<GetAgentDashboardRequest> | undefined): boolean {
    return proto3.util.equals(GetAgentDashboardRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.AgentDashboardResponse
 */
export class AgentDashboardResponse extends Message<AgentDashboardResponse> {
  /**
   * @generated from field: int64 total_commission = 1;
   */
  totalCommission = protoInt64.zero;

  /**
   * @generated from field: int64 pending_commission = 2;
   */
  pendingCommission = protoInt64.zero;

  /**
   * @generated from field: int32 subordinate_count = 3;
   */
  subordinateCount = 0;

  /**
   * @generated from field: int64 today_commission = 4;
   */
  todayCommission = protoInt64.zero;

  constructor(data?: PartialMessage<AgentDashboardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.AgentDashboardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_commission", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "pending_commission", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "subordinate_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "today_commission", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AgentDashboardResponse {
    return new AgentDashboardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AgentDashboardResponse {
    return new AgentDashboardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AgentDashboardResponse {
    return new AgentDashboardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AgentDashboardResponse | PlainMessage<AgentDashboardResponse> | undefined, b: AgentDashboardResponse | PlainMessage<AgentDashboardResponse> | undefined): boolean {
    return proto3.util.equals(AgentDashboardResponse, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CreateCommissionRequest
 */
export class CreateCommissionRequest extends Message<CreateCommissionRequest> {
  /**
   * @generated from field: int64 agent_id = 1;
   */
  agentId = protoInt64.zero;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 amount = 3;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: int64 rate = 4;
   */
  rate = protoInt64.zero;

  /**
   * @generated from field: string source = 5;
   */
  source = "";

  constructor(data?: PartialMessage<CreateCommissionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CreateCommissionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "agent_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCommissionRequest {
    return new CreateCommissionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCommissionRequest {
    return new CreateCommissionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCommissionRequest {
    return new CreateCommissionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateCommissionRequest | PlainMessage<CreateCommissionRequest> | undefined, b: CreateCommissionRequest | PlainMessage<CreateCommissionRequest> | undefined): boolean {
    return proto3.util.equals(CreateCommissionRequest, a, b);
  }
}

/**
 * @generated from message rockgame.agent.CreateCommissionResponse
 */
export class CreateCommissionResponse extends Message<CreateCommissionResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<CreateCommissionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.agent.CreateCommissionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCommissionResponse {
    return new CreateCommissionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCommissionResponse {
    return new CreateCommissionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCommissionResponse {
    return new CreateCommissionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateCommissionResponse | PlainMessage<CreateCommissionResponse> | undefined, b: CreateCommissionResponse | PlainMessage<CreateCommissionResponse> | undefined): boolean {
    return proto3.util.equals(CreateCommissionResponse, a, b);
  }
}

