// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file agent.proto (package rockgame.agent, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentDashboardResponse, AgentInfoResponse, CommissionsResponse, CreateCommissionRequest, CreateCommissionResponse, CreatePromoLinkRequest, CreatePromoLinkResponse, GetAgentDashboardRequest, GetAgentInfoRequest, GetCommissionsRequest, GetSubordinatesRequest, RequestSettlementRequest, RequestSettlementResponse, SubordinatesResponse } from "./agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AgentService handles agent/commission operations.
 * Implemented by agent-mesh.
 *
 * @generated from service rockgame.agent.AgentService
 */
export const AgentService = {
  typeName: "rockgame.agent.AgentService",
  methods: {
    /**
     * @generated from rpc rockgame.agent.AgentService.GetAgentInfo
     */
    getAgentInfo: {
      name: "GetAgentInfo",
      I: GetAgentInfoRequest,
      O: AgentInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.agent.AgentService.GetSubordinates
     */
    getSubordinates: {
      name: "GetSubordinates",
      I: GetSubordinatesRequest,
      O: SubordinatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.agent.AgentService.GetCommissions
     */
    getCommissions: {
      name: "GetCommissions",
      I: GetCommissionsRequest,
      O: CommissionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.agent.AgentService.RequestSettlement
     */
    requestSettlement: {
      name: "RequestSettlement",
      I: RequestSettlementRequest,
      O: RequestSettlementResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.agent.AgentService.CreatePromoLink
     */
    createPromoLink: {
      name: "CreatePromoLink",
      I: CreatePromoLinkRequest,
      O: CreatePromoLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.agent.AgentService.GetAgentDashboard
     */
    getAgentDashboard: {
      name: "GetAgentDashboard",
      I: GetAgentDashboardRequest,
      O: AgentDashboardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateCommission records a commission entry when a referral generates revenue.
     *
     * @generated from rpc rockgame.agent.AgentService.CreateCommission
     */
    createCommission: {
      name: "CreateCommission",
      I: CreateCommissionRequest,
      O: CreateCommissionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

