// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file event.proto (package rockgame.event, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchEventsRequest, BatchEventsResponse, GetEventStatsRequest, GetEventStatsResponse, GetEventTypesRequest, GetEventTypesResponse, GetRealtimeStatsRequest, GetRealtimeStatsResponse, TrackEventRequest, TrackEventResponse } from "./event_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * EventService handles analytics event tracking.
 * Implemented by event-node.
 *
 * @generated from service rockgame.event.EventService
 */
export const EventService = {
  typeName: "rockgame.event.EventService",
  methods: {
    /**
     * TrackEvent records a single analytics event.
     *
     * @generated from rpc rockgame.event.EventService.TrackEvent
     */
    trackEvent: {
      name: "TrackEvent",
      I: TrackEventRequest,
      O: TrackEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * BatchEvents records multiple events at once (max 100).
     *
     * @generated from rpc rockgame.event.EventService.BatchEvents
     */
    batchEvents: {
      name: "BatchEvents",
      I: BatchEventsRequest,
      O: BatchEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetEventStats returns aggregate event counts.
     *
     * @generated from rpc rockgame.event.EventService.GetEventStats
     */
    getEventStats: {
      name: "GetEventStats",
      I: GetEventStatsRequest,
      O: GetEventStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetEventTypes returns all registered event types.
     *
     * @generated from rpc rockgame.event.EventService.GetEventTypes
     */
    getEventTypes: {
      name: "GetEventTypes",
      I: GetEventTypesRequest,
      O: GetEventTypesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetRealtimeStats returns event counts in the last 5 minutes.
     *
     * @generated from rpc rockgame.event.EventService.GetRealtimeStats
     */
    getRealtimeStats: {
      name: "GetRealtimeStats",
      I: GetRealtimeStatsRequest,
      O: GetRealtimeStatsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

