// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file event.proto (package rockgame.event, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Struct } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.event.TrackEventRequest
 */
export class TrackEventRequest extends Message<TrackEventRequest> {
  /**
   * @generated from field: string event_name = 1;
   */
  eventName = "";

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: map<string, string> properties = 3;
   */
  properties: { [key: string]: string } = {};

  constructor(data?: PartialMessage<TrackEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.TrackEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "properties", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackEventRequest {
    return new TrackEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackEventRequest {
    return new TrackEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackEventRequest {
    return new TrackEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TrackEventRequest | PlainMessage<TrackEventRequest> | undefined, b: TrackEventRequest | PlainMessage<TrackEventRequest> | undefined): boolean {
    return proto3.util.equals(TrackEventRequest, a, b);
  }
}

/**
 * @generated from message rockgame.event.TrackEventResponse
 */
export class TrackEventResponse extends Message<TrackEventResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  /**
   * @generated from field: string event = 2;
   */
  event = "";

  constructor(data?: PartialMessage<TrackEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.TrackEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackEventResponse {
    return new TrackEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackEventResponse {
    return new TrackEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackEventResponse {
    return new TrackEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: TrackEventResponse | PlainMessage<TrackEventResponse> | undefined, b: TrackEventResponse | PlainMessage<TrackEventResponse> | undefined): boolean {
    return proto3.util.equals(TrackEventResponse, a, b);
  }
}

/**
 * @generated from message rockgame.event.BatchEventsRequest
 */
export class BatchEventsRequest extends Message<BatchEventsRequest> {
  /**
   * @generated from field: repeated rockgame.event.TrackEventRequest events = 1;
   */
  events: TrackEventRequest[] = [];

  constructor(data?: PartialMessage<BatchEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.BatchEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: TrackEventRequest, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchEventsRequest {
    return new BatchEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchEventsRequest {
    return new BatchEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchEventsRequest {
    return new BatchEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchEventsRequest | PlainMessage<BatchEventsRequest> | undefined, b: BatchEventsRequest | PlainMessage<BatchEventsRequest> | undefined): boolean {
    return proto3.util.equals(BatchEventsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.event.BatchEventsResponse
 */
export class BatchEventsResponse extends Message<BatchEventsResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  constructor(data?: PartialMessage<BatchEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.BatchEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchEventsResponse {
    return new BatchEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchEventsResponse {
    return new BatchEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchEventsResponse {
    return new BatchEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchEventsResponse | PlainMessage<BatchEventsResponse> | undefined, b: BatchEventsResponse | PlainMessage<BatchEventsResponse> | undefined): boolean {
    return proto3.util.equals(BatchEventsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetEventStatsRequest
 */
export class GetEventStatsRequest extends Message<GetEventStatsRequest> {
  /**
   * @generated from field: string event_name = 1;
   */
  eventName = "";

  /**
   * @generated from field: int32 hours = 2;
   */
  hours = 0;

  constructor(data?: PartialMessage<GetEventStatsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetEventStatsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "hours", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventStatsRequest {
    return new GetEventStatsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventStatsRequest {
    return new GetEventStatsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventStatsRequest {
    return new GetEventStatsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventStatsRequest | PlainMessage<GetEventStatsRequest> | undefined, b: GetEventStatsRequest | PlainMessage<GetEventStatsRequest> | undefined): boolean {
    return proto3.util.equals(GetEventStatsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.event.EventStat
 */
export class EventStat extends Message<EventStat> {
  /**
   * @generated from field: string event_name = 1;
   */
  eventName = "";

  /**
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  constructor(data?: PartialMessage<EventStat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.EventStat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventStat {
    return new EventStat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventStat {
    return new EventStat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventStat {
    return new EventStat().fromJsonString(jsonString, options);
  }

  static equals(a: EventStat | PlainMessage<EventStat> | undefined, b: EventStat | PlainMessage<EventStat> | undefined): boolean {
    return proto3.util.equals(EventStat, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetEventStatsResponse
 */
export class GetEventStatsResponse extends Message<GetEventStatsResponse> {
  /**
   * @generated from field: repeated rockgame.event.EventStat stats = 1;
   */
  stats: EventStat[] = [];

  /**
   * @generated from field: int32 hours = 2;
   */
  hours = 0;

  /**
   * @generated from field: string since = 3;
   */
  since = "";

  /**
   * @generated from field: string table = 4;
   */
  table = "";

  constructor(data?: PartialMessage<GetEventStatsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetEventStatsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stats", kind: "message", T: EventStat, repeated: true },
    { no: 2, name: "hours", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "since", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "table", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventStatsResponse {
    return new GetEventStatsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventStatsResponse {
    return new GetEventStatsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventStatsResponse {
    return new GetEventStatsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventStatsResponse | PlainMessage<GetEventStatsResponse> | undefined, b: GetEventStatsResponse | PlainMessage<GetEventStatsResponse> | undefined): boolean {
    return proto3.util.equals(GetEventStatsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetEventTypesRequest
 */
export class GetEventTypesRequest extends Message<GetEventTypesRequest> {
  constructor(data?: PartialMessage<GetEventTypesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetEventTypesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventTypesRequest {
    return new GetEventTypesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventTypesRequest {
    return new GetEventTypesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventTypesRequest {
    return new GetEventTypesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventTypesRequest | PlainMessage<GetEventTypesRequest> | undefined, b: GetEventTypesRequest | PlainMessage<GetEventTypesRequest> | undefined): boolean {
    return proto3.util.equals(GetEventTypesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.event.EventTypeInfo
 */
export class EventTypeInfo extends Message<EventTypeInfo> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string category = 3;
   */
  category = "";

  constructor(data?: PartialMessage<EventTypeInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.EventTypeInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTypeInfo {
    return new EventTypeInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTypeInfo {
    return new EventTypeInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTypeInfo {
    return new EventTypeInfo().fromJsonString(jsonString, options);
  }

  static equals(a: EventTypeInfo | PlainMessage<EventTypeInfo> | undefined, b: EventTypeInfo | PlainMessage<EventTypeInfo> | undefined): boolean {
    return proto3.util.equals(EventTypeInfo, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetEventTypesResponse
 */
export class GetEventTypesResponse extends Message<GetEventTypesResponse> {
  /**
   * @generated from field: repeated rockgame.event.EventTypeInfo types = 1;
   */
  types: EventTypeInfo[] = [];

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  constructor(data?: PartialMessage<GetEventTypesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetEventTypesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "types", kind: "message", T: EventTypeInfo, repeated: true },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventTypesResponse {
    return new GetEventTypesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventTypesResponse {
    return new GetEventTypesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventTypesResponse {
    return new GetEventTypesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventTypesResponse | PlainMessage<GetEventTypesResponse> | undefined, b: GetEventTypesResponse | PlainMessage<GetEventTypesResponse> | undefined): boolean {
    return proto3.util.equals(GetEventTypesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetRealtimeStatsRequest
 */
export class GetRealtimeStatsRequest extends Message<GetRealtimeStatsRequest> {
  constructor(data?: PartialMessage<GetRealtimeStatsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetRealtimeStatsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRealtimeStatsRequest {
    return new GetRealtimeStatsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRealtimeStatsRequest {
    return new GetRealtimeStatsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRealtimeStatsRequest {
    return new GetRealtimeStatsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRealtimeStatsRequest | PlainMessage<GetRealtimeStatsRequest> | undefined, b: GetRealtimeStatsRequest | PlainMessage<GetRealtimeStatsRequest> | undefined): boolean {
    return proto3.util.equals(GetRealtimeStatsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.event.GetRealtimeStatsResponse
 */
export class GetRealtimeStatsResponse extends Message<GetRealtimeStatsResponse> {
  /**
   * @generated from field: google.protobuf.Struct events = 1;
   */
  events?: Struct;

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: string window = 3;
   */
  window = "";

  /**
   * @generated from field: string timestamp = 4;
   */
  timestamp = "";

  constructor(data?: PartialMessage<GetRealtimeStatsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.event.GetRealtimeStatsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: Struct },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "window", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRealtimeStatsResponse {
    return new GetRealtimeStatsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRealtimeStatsResponse {
    return new GetRealtimeStatsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRealtimeStatsResponse {
    return new GetRealtimeStatsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRealtimeStatsResponse | PlainMessage<GetRealtimeStatsResponse> | undefined, b: GetRealtimeStatsResponse | PlainMessage<GetRealtimeStatsResponse> | undefined): boolean {
    return proto3.util.equals(GetRealtimeStatsResponse, a, b);
  }
}

