// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file game.proto (package rockgame.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ReloadConfigsRequest, ReloadConfigsResponse, SyncVendorGamesRequest, SyncVendorGamesResponse } from "./game_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * VendorService handles vendor-related operations (sync, health, etc.).
 *
 * @generated from service rockgame.game.VendorService
 */
export const VendorService = {
  typeName: "rockgame.game.VendorService",
  methods: {
    /**
     * SyncVendorGames fetches games from a vendor and upserts into game_info.
     *
     * @generated from rpc rockgame.game.VendorService.SyncVendorGames
     */
    syncVendorGames: {
      name: "SyncVendorGames",
      I: SyncVendorGamesRequest,
      O: SyncVendorGamesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * GameService handles game-related operations (config reload, etc.).
 *
 * @generated from service rockgame.game.GameService
 */
export const GameService = {
  typeName: "rockgame.game.GameService",
  methods: {
    /**
     * ReloadConfigs reloads game configuration from the database into memory.
     *
     * @generated from rpc rockgame.game.GameService.ReloadConfigs
     */
    reloadConfigs: {
      name: "ReloadConfigs",
      I: ReloadConfigsRequest,
      O: ReloadConfigsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

