// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file game.proto (package rockgame.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.game.SyncVendorGamesRequest
 */
export class SyncVendorGamesRequest extends Message<SyncVendorGamesRequest> {
  /**
   * @generated from field: int64 vendor_id = 1;
   */
  vendorId = protoInt64.zero;

  constructor(data?: PartialMessage<SyncVendorGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.game.SyncVendorGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SyncVendorGamesRequest {
    return new SyncVendorGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SyncVendorGamesRequest {
    return new SyncVendorGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SyncVendorGamesRequest {
    return new SyncVendorGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SyncVendorGamesRequest | PlainMessage<SyncVendorGamesRequest> | undefined, b: SyncVendorGamesRequest | PlainMessage<SyncVendorGamesRequest> | undefined): boolean {
    return proto3.util.equals(SyncVendorGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.game.SyncVendorGamesResponse
 */
export class SyncVendorGamesResponse extends Message<SyncVendorGamesResponse> {
  /**
   * @generated from field: string vendor = 1;
   */
  vendor = "";

  /**
   * @generated from field: int32 synced_count = 2;
   */
  syncedCount = 0;

  constructor(data?: PartialMessage<SyncVendorGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.game.SyncVendorGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vendor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "synced_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SyncVendorGamesResponse {
    return new SyncVendorGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SyncVendorGamesResponse {
    return new SyncVendorGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SyncVendorGamesResponse {
    return new SyncVendorGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SyncVendorGamesResponse | PlainMessage<SyncVendorGamesResponse> | undefined, b: SyncVendorGamesResponse | PlainMessage<SyncVendorGamesResponse> | undefined): boolean {
    return proto3.util.equals(SyncVendorGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.game.ReloadConfigsRequest
 */
export class ReloadConfigsRequest extends Message<ReloadConfigsRequest> {
  constructor(data?: PartialMessage<ReloadConfigsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.game.ReloadConfigsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReloadConfigsRequest {
    return new ReloadConfigsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReloadConfigsRequest {
    return new ReloadConfigsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReloadConfigsRequest {
    return new ReloadConfigsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReloadConfigsRequest | PlainMessage<ReloadConfigsRequest> | undefined, b: ReloadConfigsRequest | PlainMessage<ReloadConfigsRequest> | undefined): boolean {
    return proto3.util.equals(ReloadConfigsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.game.ReloadConfigsResponse
 */
export class ReloadConfigsResponse extends Message<ReloadConfigsResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  constructor(data?: PartialMessage<ReloadConfigsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.game.ReloadConfigsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReloadConfigsResponse {
    return new ReloadConfigsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReloadConfigsResponse {
    return new ReloadConfigsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReloadConfigsResponse {
    return new ReloadConfigsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReloadConfigsResponse | PlainMessage<ReloadConfigsResponse> | undefined, b: ReloadConfigsResponse | PlainMessage<ReloadConfigsResponse> | undefined): boolean {
    return proto3.util.equals(ReloadConfigsResponse, a, b);
  }
}

