// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file game_manager.proto (package rockgame.gamemanager, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.gamemanager.GetLobbyBannersRequest
 */
export class GetLobbyBannersRequest extends Message<GetLobbyBannersRequest> {
  constructor(data?: PartialMessage<GetLobbyBannersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetLobbyBannersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyBannersRequest | PlainMessage<GetLobbyBannersRequest> | undefined, b: GetLobbyBannersRequest | PlainMessage<GetLobbyBannersRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyBannersRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyBanner
 */
export class LobbyBanner extends Message<LobbyBanner> {
  /**
   * @generated from field: int64 number = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string image_url = 3;
   */
  imageUrl = "";

  /**
   * @generated from field: string link_url = 4;
   */
  linkUrl = "";

  /**
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<LobbyBanner>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyBanner";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "number", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "link_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyBanner {
    return new LobbyBanner().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyBanner {
    return new LobbyBanner().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyBanner {
    return new LobbyBanner().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyBanner | PlainMessage<LobbyBanner> | undefined, b: LobbyBanner | PlainMessage<LobbyBanner> | undefined): boolean {
    return proto3.util.equals(LobbyBanner, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyBannersResponse
 */
export class LobbyBannersResponse extends Message<LobbyBannersResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.LobbyBanner banners = 1;
   */
  banners: LobbyBanner[] = [];

  constructor(data?: PartialMessage<LobbyBannersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyBannersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "banners", kind: "message", T: LobbyBanner, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyBannersResponse | PlainMessage<LobbyBannersResponse> | undefined, b: LobbyBannersResponse | PlainMessage<LobbyBannersResponse> | undefined): boolean {
    return proto3.util.equals(LobbyBannersResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetLobbySplashRequest
 */
export class GetLobbySplashRequest extends Message<GetLobbySplashRequest> {
  constructor(data?: PartialMessage<GetLobbySplashRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetLobbySplashRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbySplashRequest | PlainMessage<GetLobbySplashRequest> | undefined, b: GetLobbySplashRequest | PlainMessage<GetLobbySplashRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbySplashRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbySplash
 */
export class LobbySplash extends Message<LobbySplash> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  /**
   * @generated from field: string image_url = 4;
   */
  imageUrl = "";

  /**
   * @generated from field: string link_url = 5;
   */
  linkUrl = "";

  /**
   * @generated from field: int32 daily_limit = 6;
   */
  dailyLimit = 0;

  /**
   * @generated from field: int32 priority = 7;
   */
  priority = 0;

  constructor(data?: PartialMessage<LobbySplash>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbySplash";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "link_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "daily_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "priority", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbySplash {
    return new LobbySplash().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbySplash {
    return new LobbySplash().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbySplash {
    return new LobbySplash().fromJsonString(jsonString, options);
  }

  static equals(a: LobbySplash | PlainMessage<LobbySplash> | undefined, b: LobbySplash | PlainMessage<LobbySplash> | undefined): boolean {
    return proto3.util.equals(LobbySplash, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbySplashResponse
 */
export class LobbySplashResponse extends Message<LobbySplashResponse> {
  /**
   * @generated from field: rockgame.gamemanager.LobbySplash splash = 1;
   */
  splash?: LobbySplash;

  constructor(data?: PartialMessage<LobbySplashResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbySplashResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "splash", kind: "message", T: LobbySplash },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbySplashResponse | PlainMessage<LobbySplashResponse> | undefined, b: LobbySplashResponse | PlainMessage<LobbySplashResponse> | undefined): boolean {
    return proto3.util.equals(LobbySplashResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetLobbyConfigRequest
 */
export class GetLobbyConfigRequest extends Message<GetLobbyConfigRequest> {
  constructor(data?: PartialMessage<GetLobbyConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetLobbyConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyConfigRequest | PlainMessage<GetLobbyConfigRequest> | undefined, b: GetLobbyConfigRequest | PlainMessage<GetLobbyConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyConfigRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyConfigResponse
 */
export class LobbyConfigResponse extends Message<LobbyConfigResponse> {
  /**
   * @generated from field: string version = 1;
   */
  version = "";

  /**
   * @generated from field: string configs = 2;
   */
  configs = "";

  constructor(data?: PartialMessage<LobbyConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "configs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyConfigResponse | PlainMessage<LobbyConfigResponse> | undefined, b: LobbyConfigResponse | PlainMessage<LobbyConfigResponse> | undefined): boolean {
    return proto3.util.equals(LobbyConfigResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetLobbyCategoriesRequest
 */
export class GetLobbyCategoriesRequest extends Message<GetLobbyCategoriesRequest> {
  constructor(data?: PartialMessage<GetLobbyCategoriesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetLobbyCategoriesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyCategoriesRequest | PlainMessage<GetLobbyCategoriesRequest> | undefined, b: GetLobbyCategoriesRequest | PlainMessage<GetLobbyCategoriesRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyCategoriesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyCategory
 */
export class LobbyCategory extends Message<LobbyCategory> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 lobby_id = 2;
   */
  lobbyId = protoInt64.zero;

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string icon = 4;
   */
  icon = "";

  /**
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder = 0;

  /**
   * @generated from field: int64 game_count = 6;
   */
  gameCount = protoInt64.zero;

  constructor(data?: PartialMessage<LobbyCategory>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyCategory";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "lobby_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "game_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyCategory {
    return new LobbyCategory().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyCategory {
    return new LobbyCategory().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyCategory {
    return new LobbyCategory().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyCategory | PlainMessage<LobbyCategory> | undefined, b: LobbyCategory | PlainMessage<LobbyCategory> | undefined): boolean {
    return proto3.util.equals(LobbyCategory, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyCategoriesResponse
 */
export class LobbyCategoriesResponse extends Message<LobbyCategoriesResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.LobbyCategory categories = 1;
   */
  categories: LobbyCategory[] = [];

  constructor(data?: PartialMessage<LobbyCategoriesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyCategoriesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "categories", kind: "message", T: LobbyCategory, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyCategoriesResponse | PlainMessage<LobbyCategoriesResponse> | undefined, b: LobbyCategoriesResponse | PlainMessage<LobbyCategoriesResponse> | undefined): boolean {
    return proto3.util.equals(LobbyCategoriesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetGameVendorsRequest
 */
export class GetGameVendorsRequest extends Message<GetGameVendorsRequest> {
  constructor(data?: PartialMessage<GetGameVendorsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetGameVendorsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameVendorsRequest | PlainMessage<GetGameVendorsRequest> | undefined, b: GetGameVendorsRequest | PlainMessage<GetGameVendorsRequest> | undefined): boolean {
    return proto3.util.equals(GetGameVendorsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GameVendor
 */
export class GameVendor extends Message<GameVendor> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string logo = 3;
   */
  logo = "";

  constructor(data?: PartialMessage<GameVendor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GameVendor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameVendor {
    return new GameVendor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameVendor {
    return new GameVendor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameVendor {
    return new GameVendor().fromJsonString(jsonString, options);
  }

  static equals(a: GameVendor | PlainMessage<GameVendor> | undefined, b: GameVendor | PlainMessage<GameVendor> | undefined): boolean {
    return proto3.util.equals(GameVendor, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GameVendorsResponse
 */
export class GameVendorsResponse extends Message<GameVendorsResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.GameVendor vendors = 1;
   */
  vendors: GameVendor[] = [];

  constructor(data?: PartialMessage<GameVendorsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GameVendorsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vendors", kind: "message", T: GameVendor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameVendorsResponse | PlainMessage<GameVendorsResponse> | undefined, b: GameVendorsResponse | PlainMessage<GameVendorsResponse> | undefined): boolean {
    return proto3.util.equals(GameVendorsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetLobbyGamesRequest
 */
export class GetLobbyGamesRequest extends Message<GetLobbyGamesRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string category_id = 3;
   */
  categoryId = "";

  /**
   * @generated from field: string vendor_id = 4;
   */
  vendorId = "";

  /**
   * @generated from field: string keyword = 5;
   */
  keyword = "";

  constructor(data?: PartialMessage<GetLobbyGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetLobbyGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "vendor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyGamesRequest | PlainMessage<GetLobbyGamesRequest> | undefined, b: GetLobbyGamesRequest | PlainMessage<GetLobbyGamesRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyGame
 */
export class LobbyGame extends Message<LobbyGame> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 vendor_id = 2;
   */
  vendorId = protoInt64.zero;

  /**
   * @generated from field: string game_id = 3;
   */
  gameId = "";

  /**
   * @generated from field: string name = 4;
   */
  name = "";

  /**
   * @generated from field: string icon = 5;
   */
  icon = "";

  /**
   * @generated from field: string url = 6;
   */
  url = "";

  /**
   * @generated from field: int64 category_id = 7;
   */
  categoryId = protoInt64.zero;

  /**
   * @generated from field: int32 status = 8;
   */
  status = 0;

  /**
   * @generated from field: int32 sort_order = 9;
   */
  sortOrder = 0;

  /**
   * @generated from field: int32 hot = 10;
   */
  hot = 0;

  /**
   * @generated from field: int32 is_new = 11;
   */
  isNew = 0;

  /**
   * @generated from field: string vendor_name = 12;
   */
  vendorName = "";

  constructor(data?: PartialMessage<LobbyGame>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyGame";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "category_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "hot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "is_new", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "vendor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyGame {
    return new LobbyGame().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyGame {
    return new LobbyGame().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyGame {
    return new LobbyGame().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyGame | PlainMessage<LobbyGame> | undefined, b: LobbyGame | PlainMessage<LobbyGame> | undefined): boolean {
    return proto3.util.equals(LobbyGame, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.LobbyGamesResponse
 */
export class LobbyGamesResponse extends Message<LobbyGamesResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.LobbyGame games = 1;
   */
  games: LobbyGame[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<LobbyGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.LobbyGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "games", kind: "message", T: LobbyGame, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyGamesResponse | PlainMessage<LobbyGamesResponse> | undefined, b: LobbyGamesResponse | PlainMessage<LobbyGamesResponse> | undefined): boolean {
    return proto3.util.equals(LobbyGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GetGameListRequest
 */
export class GetGameListRequest extends Message<GetGameListRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string category_id = 3;
   */
  categoryId = "";

  /**
   * @generated from field: string vendor_id = 4;
   */
  vendorId = "";

  /**
   * @generated from field: string game_type = 5;
   */
  gameType = "";

  /**
   * @generated from field: string keyword = 6;
   */
  keyword = "";

  /**
   * @generated from field: bool hot = 7;
   */
  hot = false;

  /**
   * @generated from field: bool is_new = 8;
   */
  isNew = false;

  constructor(data?: PartialMessage<GetGameListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GetGameListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "vendor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "hot", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "is_new", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameListRequest | PlainMessage<GetGameListRequest> | undefined, b: GetGameListRequest | PlainMessage<GetGameListRequest> | undefined): boolean {
    return proto3.util.equals(GetGameListRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GameListItem
 */
export class GameListItem extends Message<GameListItem> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string icon = 3;
   */
  icon = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string launch_url = 5;
   */
  launchUrl = "";

  /**
   * @generated from field: int64 category_id = 6;
   */
  categoryId = protoInt64.zero;

  /**
   * @generated from field: int64 vendor_id = 7;
   */
  vendorId = protoInt64.zero;

  /**
   * @generated from field: string game_type = 8;
   */
  gameType = "";

  /**
   * @generated from field: string game_id = 9;
   */
  gameId = "";

  /**
   * @generated from field: int32 hot = 10;
   */
  hot = 0;

  /**
   * @generated from field: int32 is_new = 11;
   */
  isNew = 0;

  /**
   * @generated from field: int32 sort_order = 12;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<GameListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GameListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "launch_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "category_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "hot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "is_new", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameListItem {
    return new GameListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJsonString(jsonString, options);
  }

  static equals(a: GameListItem | PlainMessage<GameListItem> | undefined, b: GameListItem | PlainMessage<GameListItem> | undefined): boolean {
    return proto3.util.equals(GameListItem, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.GameListResponse
 */
export class GameListResponse extends Message<GameListResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: bool has_more = 5;
   */
  hasMore = false;

  constructor(data?: PartialMessage<GameListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.GameListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "has_more", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameListResponse {
    return new GameListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameListResponse {
    return new GameListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameListResponse {
    return new GameListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameListResponse | PlainMessage<GameListResponse> | undefined, b: GameListResponse | PlainMessage<GameListResponse> | undefined): boolean {
    return proto3.util.equals(GameListResponse, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.SearchGamesRequest
 */
export class SearchGamesRequest extends Message<SearchGamesRequest> {
  /**
   * @generated from field: string keyword = 1;
   */
  keyword = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<SearchGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.SearchGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchGamesRequest | PlainMessage<SearchGamesRequest> | undefined, b: SearchGamesRequest | PlainMessage<SearchGamesRequest> | undefined): boolean {
    return proto3.util.equals(SearchGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.gamemanager.SearchGamesResponse
 */
export class SearchGamesResponse extends Message<SearchGamesResponse> {
  /**
   * @generated from field: repeated rockgame.gamemanager.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  constructor(data?: PartialMessage<SearchGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.gamemanager.SearchGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchGamesResponse | PlainMessage<SearchGamesResponse> | undefined, b: SearchGamesResponse | PlainMessage<SearchGamesResponse> | undefined): boolean {
    return proto3.util.equals(SearchGamesResponse, a, b);
  }
}
