// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file gateway.proto (package rockgame.gateway, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ForwardRequest, ForwardResponse } from "./gateway_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * GatewayService is a generic gRPC service that wraps HTTP request/response.
 * Each backend service implements this to handle forwarded requests from Gate.
 * This avoids needing individual proto files for each backend service.
 *
 * @generated from service rockgame.gateway.GatewayService
 */
export const GatewayService = {
  typeName: "rockgame.gateway.GatewayService",
  methods: {
    /**
     * Forward sends an HTTP request to the backend and returns the response.
     *
     * @generated from rpc rockgame.gateway.GatewayService.Forward
     */
    forward: {
      name: "Forward",
      I: ForwardRequest,
      O: ForwardResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

