// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file lobby.proto (package rockgame.lobby, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.lobby.GetGameVendorsRequest
 */
export class GetGameVendorsRequest extends Message<GetGameVendorsRequest> {
  constructor(data?: PartialMessage<GetGameVendorsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetGameVendorsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameVendorsRequest {
    return new GetGameVendorsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameVendorsRequest | PlainMessage<GetGameVendorsRequest> | undefined, b: GetGameVendorsRequest | PlainMessage<GetGameVendorsRequest> | undefined): boolean {
    return proto3.util.equals(GetGameVendorsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameVendor
 */
export class GameVendor extends Message<GameVendor> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string logo = 3;
   */
  logo = "";

  constructor(data?: PartialMessage<GameVendor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameVendor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameVendor {
    return new GameVendor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameVendor {
    return new GameVendor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameVendor {
    return new GameVendor().fromJsonString(jsonString, options);
  }

  static equals(a: GameVendor | PlainMessage<GameVendor> | undefined, b: GameVendor | PlainMessage<GameVendor> | undefined): boolean {
    return proto3.util.equals(GameVendor, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameVendorsResponse
 */
export class GameVendorsResponse extends Message<GameVendorsResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.GameVendor vendors = 1;
   */
  vendors: GameVendor[] = [];

  constructor(data?: PartialMessage<GameVendorsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameVendorsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vendors", kind: "message", T: GameVendor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameVendorsResponse {
    return new GameVendorsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameVendorsResponse | PlainMessage<GameVendorsResponse> | undefined, b: GameVendorsResponse | PlainMessage<GameVendorsResponse> | undefined): boolean {
    return proto3.util.equals(GameVendorsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetGameListRequest
 */
export class GetGameListRequest extends Message<GetGameListRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string category_id = 3;
   */
  categoryId = "";

  /**
   * @generated from field: string vendor_id = 4;
   */
  vendorId = "";

  /**
   * @generated from field: string game_type = 5;
   */
  gameType = "";

  /**
   * @generated from field: string keyword = 6;
   */
  keyword = "";

  /**
   * @generated from field: bool hot = 7;
   */
  hot = false;

  /**
   * @generated from field: bool new = 8;
   */
  new = false;

  constructor(data?: PartialMessage<GetGameListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetGameListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "vendor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "hot", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "new", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameListRequest {
    return new GetGameListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameListRequest | PlainMessage<GetGameListRequest> | undefined, b: GetGameListRequest | PlainMessage<GetGameListRequest> | undefined): boolean {
    return proto3.util.equals(GetGameListRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameListItem
 */
export class GameListItem extends Message<GameListItem> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string icon = 3;
   */
  icon = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string launch_url = 5;
   */
  launchUrl = "";

  /**
   * @generated from field: int64 category_id = 6;
   */
  categoryId = protoInt64.zero;

  /**
   * @generated from field: int64 vendor_id = 7;
   */
  vendorId = protoInt64.zero;

  /**
   * @generated from field: string game_type = 8;
   */
  gameType = "";

  /**
   * @generated from field: string game_id = 9;
   */
  gameId = "";

  /**
   * @generated from field: int32 hot = 10;
   */
  hot = 0;

  /**
   * @generated from field: int32 new = 11;
   */
  new = 0;

  /**
   * @generated from field: int32 sort_order = 12;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<GameListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "launch_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "category_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "hot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "new", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameListItem {
    return new GameListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJsonString(jsonString, options);
  }

  static equals(a: GameListItem | PlainMessage<GameListItem> | undefined, b: GameListItem | PlainMessage<GameListItem> | undefined): boolean {
    return proto3.util.equals(GameListItem, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameListResponse
 */
export class GameListResponse extends Message<GameListResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: bool has_more = 5;
   */
  hasMore = false;

  constructor(data?: PartialMessage<GameListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "has_more", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameListResponse {
    return new GameListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameListResponse {
    return new GameListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameListResponse {
    return new GameListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameListResponse | PlainMessage<GameListResponse> | undefined, b: GameListResponse | PlainMessage<GameListResponse> | undefined): boolean {
    return proto3.util.equals(GameListResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.SearchGamesRequest
 */
export class SearchGamesRequest extends Message<SearchGamesRequest> {
  /**
   * @generated from field: string keyword = 1;
   */
  keyword = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<SearchGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.SearchGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchGamesRequest {
    return new SearchGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchGamesRequest | PlainMessage<SearchGamesRequest> | undefined, b: SearchGamesRequest | PlainMessage<SearchGamesRequest> | undefined): boolean {
    return proto3.util.equals(SearchGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.SearchGamesResponse
 */
export class SearchGamesResponse extends Message<SearchGamesResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  constructor(data?: PartialMessage<SearchGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.SearchGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchGamesResponse {
    return new SearchGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchGamesResponse | PlainMessage<SearchGamesResponse> | undefined, b: SearchGamesResponse | PlainMessage<SearchGamesResponse> | undefined): boolean {
    return proto3.util.equals(SearchGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.ToggleFavoriteRequest
 */
export class ToggleFavoriteRequest extends Message<ToggleFavoriteRequest> {
  /**
   * @generated from field: int64 game_id = 1;
   */
  gameId = protoInt64.zero;

  constructor(data?: PartialMessage<ToggleFavoriteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.ToggleFavoriteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ToggleFavoriteRequest | PlainMessage<ToggleFavoriteRequest> | undefined, b: ToggleFavoriteRequest | PlainMessage<ToggleFavoriteRequest> | undefined): boolean {
    return proto3.util.equals(ToggleFavoriteRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.ToggleFavoriteResponse
 */
export class ToggleFavoriteResponse extends Message<ToggleFavoriteResponse> {
  /**
   * @generated from field: int64 game_id = 1;
   */
  gameId = protoInt64.zero;

  /**
   * @generated from field: bool favorited = 2;
   */
  favorited = false;

  constructor(data?: PartialMessage<ToggleFavoriteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.ToggleFavoriteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "favorited", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ToggleFavoriteResponse | PlainMessage<ToggleFavoriteResponse> | undefined, b: ToggleFavoriteResponse | PlainMessage<ToggleFavoriteResponse> | undefined): boolean {
    return proto3.util.equals(ToggleFavoriteResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetRecentGamesRequest
 */
export class GetRecentGamesRequest extends Message<GetRecentGamesRequest> {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit = 0;

  constructor(data?: PartialMessage<GetRecentGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetRecentGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRecentGamesRequest | PlainMessage<GetRecentGamesRequest> | undefined, b: GetRecentGamesRequest | PlainMessage<GetRecentGamesRequest> | undefined): boolean {
    return proto3.util.equals(GetRecentGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.RecentGamesResponse
 */
export class RecentGamesResponse extends Message<RecentGamesResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  constructor(data?: PartialMessage<RecentGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.RecentGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RecentGamesResponse | PlainMessage<RecentGamesResponse> | undefined, b: RecentGamesResponse | PlainMessage<RecentGamesResponse> | undefined): boolean {
    return proto3.util.equals(RecentGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetGameHistoryRequest
 */
export class GetGameHistoryRequest extends Message<GetGameHistoryRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: int32 page = 2;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<GetGameHistoryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetGameHistoryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameHistoryRequest | PlainMessage<GetGameHistoryRequest> | undefined, b: GetGameHistoryRequest | PlainMessage<GetGameHistoryRequest> | undefined): boolean {
    return proto3.util.equals(GetGameHistoryRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameHistoryItem
 */
export class GameHistoryItem extends Message<GameHistoryItem> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string game_type = 2;
   */
  gameType = "";

  /**
   * @generated from field: string game_id = 3;
   */
  gameId = "";

  /**
   * @generated from field: int64 bet_amount = 4;
   */
  betAmount = protoInt64.zero;

  /**
   * @generated from field: int64 win_amount = 5;
   */
  winAmount = protoInt64.zero;

  /**
   * @generated from field: int64 net = 6;
   */
  net = protoInt64.zero;

  /**
   * @generated from field: string status = 7;
   */
  status = "";

  /**
   * @generated from field: bool is_free_spin = 8;
   */
  isFreeSpin = false;

  /**
   * @generated from field: int32 duration = 9;
   */
  duration = 0;

  /**
   * @generated from field: repeated int64 player_ids = 10;
   */
  playerIds: bigint[] = [];

  /**
   * @generated from field: int64 winner_id = 11;
   */
  winnerId = protoInt64.zero;

  /**
   * @generated from field: string hand_rank = 12;
   */
  handRank = "";

  /**
   * @generated from field: int64 rake = 13;
   */
  rake = protoInt64.zero;

  /**
   * @generated from field: string created_at = 14;
   */
  createdAt = "";

  constructor(data?: PartialMessage<GameHistoryItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameHistoryItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "bet_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "win_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "net", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "is_free_spin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "duration", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "player_ids", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
    { no: 11, name: "winner_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "hand_rank", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "rake", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 14, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromJsonString(jsonString, options);
  }

  static equals(a: GameHistoryItem | PlainMessage<GameHistoryItem> | undefined, b: GameHistoryItem | PlainMessage<GameHistoryItem> | undefined): boolean {
    return proto3.util.equals(GameHistoryItem, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GameHistoryResponse
 */
export class GameHistoryResponse extends Message<GameHistoryResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.GameHistoryItem list = 1;
   */
  list: GameHistoryItem[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: bool has_more = 5;
   */
  hasMore = false;

  constructor(data?: PartialMessage<GameHistoryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GameHistoryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameHistoryItem, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "has_more", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameHistoryResponse | PlainMessage<GameHistoryResponse> | undefined, b: GameHistoryResponse | PlainMessage<GameHistoryResponse> | undefined): boolean {
    return proto3.util.equals(GameHistoryResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.EndGameSessionRequest
 */
export class EndGameSessionRequest extends Message<EndGameSessionRequest> {
  /**
   * @generated from field: string session_token = 1;
   */
  sessionToken = "";

  constructor(data?: PartialMessage<EndGameSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.EndGameSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EndGameSessionRequest | PlainMessage<EndGameSessionRequest> | undefined, b: EndGameSessionRequest | PlainMessage<EndGameSessionRequest> | undefined): boolean {
    return proto3.util.equals(EndGameSessionRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.EndGameSessionResponse
 */
export class EndGameSessionResponse extends Message<EndGameSessionResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  constructor(data?: PartialMessage<EndGameSessionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.EndGameSessionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EndGameSessionResponse | PlainMessage<EndGameSessionResponse> | undefined, b: EndGameSessionResponse | PlainMessage<EndGameSessionResponse> | undefined): boolean {
    return proto3.util.equals(EndGameSessionResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetLobbyBannersRequest
 */
export class GetLobbyBannersRequest extends Message<GetLobbyBannersRequest> {
  constructor(data?: PartialMessage<GetLobbyBannersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetLobbyBannersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyBannersRequest {
    return new GetLobbyBannersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyBannersRequest | PlainMessage<GetLobbyBannersRequest> | undefined, b: GetLobbyBannersRequest | PlainMessage<GetLobbyBannersRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyBannersRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyBanner
 */
export class LobbyBanner extends Message<LobbyBanner> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string image_url = 3;
   */
  imageUrl = "";

  /**
   * @generated from field: string link_url = 4;
   */
  linkUrl = "";

  /**
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<LobbyBanner>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyBanner";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "link_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyBanner {
    return new LobbyBanner().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyBanner {
    return new LobbyBanner().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyBanner {
    return new LobbyBanner().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyBanner | PlainMessage<LobbyBanner> | undefined, b: LobbyBanner | PlainMessage<LobbyBanner> | undefined): boolean {
    return proto3.util.equals(LobbyBanner, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyBannersResponse
 */
export class LobbyBannersResponse extends Message<LobbyBannersResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.LobbyBanner banners = 1;
   */
  banners: LobbyBanner[] = [];

  constructor(data?: PartialMessage<LobbyBannersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyBannersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "banners", kind: "message", T: LobbyBanner, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyBannersResponse {
    return new LobbyBannersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyBannersResponse | PlainMessage<LobbyBannersResponse> | undefined, b: LobbyBannersResponse | PlainMessage<LobbyBannersResponse> | undefined): boolean {
    return proto3.util.equals(LobbyBannersResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetLobbyCategoriesRequest
 */
export class GetLobbyCategoriesRequest extends Message<GetLobbyCategoriesRequest> {
  constructor(data?: PartialMessage<GetLobbyCategoriesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetLobbyCategoriesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyCategoriesRequest {
    return new GetLobbyCategoriesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyCategoriesRequest | PlainMessage<GetLobbyCategoriesRequest> | undefined, b: GetLobbyCategoriesRequest | PlainMessage<GetLobbyCategoriesRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyCategoriesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyCategory
 */
export class LobbyCategory extends Message<LobbyCategory> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 lobby_id = 2;
   */
  lobbyId = protoInt64.zero;

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string icon = 4;
   */
  icon = "";

  /**
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder = 0;

  /**
   * @generated from field: int64 game_count = 6;
   */
  gameCount = protoInt64.zero;

  constructor(data?: PartialMessage<LobbyCategory>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyCategory";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "lobby_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "game_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyCategory {
    return new LobbyCategory().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyCategory {
    return new LobbyCategory().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyCategory {
    return new LobbyCategory().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyCategory | PlainMessage<LobbyCategory> | undefined, b: LobbyCategory | PlainMessage<LobbyCategory> | undefined): boolean {
    return proto3.util.equals(LobbyCategory, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyCategoriesResponse
 */
export class LobbyCategoriesResponse extends Message<LobbyCategoriesResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.LobbyCategory categories = 1;
   */
  categories: LobbyCategory[] = [];

  constructor(data?: PartialMessage<LobbyCategoriesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyCategoriesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "categories", kind: "message", T: LobbyCategory, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyCategoriesResponse {
    return new LobbyCategoriesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyCategoriesResponse | PlainMessage<LobbyCategoriesResponse> | undefined, b: LobbyCategoriesResponse | PlainMessage<LobbyCategoriesResponse> | undefined): boolean {
    return proto3.util.equals(LobbyCategoriesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetLobbyGamesRequest
 */
export class GetLobbyGamesRequest extends Message<GetLobbyGamesRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string category_id = 3;
   */
  categoryId = "";

  /**
   * @generated from field: string vendor_id = 4;
   */
  vendorId = "";

  /**
   * @generated from field: string keyword = 5;
   */
  keyword = "";

  constructor(data?: PartialMessage<GetLobbyGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetLobbyGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "vendor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyGamesRequest {
    return new GetLobbyGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyGamesRequest | PlainMessage<GetLobbyGamesRequest> | undefined, b: GetLobbyGamesRequest | PlainMessage<GetLobbyGamesRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyGame
 */
export class LobbyGame extends Message<LobbyGame> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int64 vendor_id = 2;
   */
  vendorId = protoInt64.zero;

  /**
   * @generated from field: string game_id = 3;
   */
  gameId = "";

  /**
   * @generated from field: string name = 4;
   */
  name = "";

  /**
   * @generated from field: string icon = 5;
   */
  icon = "";

  /**
   * @generated from field: string url = 6;
   */
  url = "";

  /**
   * @generated from field: int64 category_id = 7;
   */
  categoryId = protoInt64.zero;

  /**
   * @generated from field: int32 status = 8;
   */
  status = 0;

  /**
   * @generated from field: int32 sort_order = 9;
   */
  sortOrder = 0;

  /**
   * @generated from field: int32 hot = 10;
   */
  hot = 0;

  /**
   * @generated from field: int32 new = 11;
   */
  new = 0;

  /**
   * @generated from field: string vendor_name = 12;
   */
  vendorName = "";

  constructor(data?: PartialMessage<LobbyGame>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyGame";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "category_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "hot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "new", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "vendor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyGame {
    return new LobbyGame().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyGame {
    return new LobbyGame().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyGame {
    return new LobbyGame().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyGame | PlainMessage<LobbyGame> | undefined, b: LobbyGame | PlainMessage<LobbyGame> | undefined): boolean {
    return proto3.util.equals(LobbyGame, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyGamesResponse
 */
export class LobbyGamesResponse extends Message<LobbyGamesResponse> {
  /**
   * @generated from field: repeated rockgame.lobby.LobbyGame games = 1;
   */
  games: LobbyGame[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<LobbyGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "games", kind: "message", T: LobbyGame, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyGamesResponse {
    return new LobbyGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyGamesResponse | PlainMessage<LobbyGamesResponse> | undefined, b: LobbyGamesResponse | PlainMessage<LobbyGamesResponse> | undefined): boolean {
    return proto3.util.equals(LobbyGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetLobbyConfigRequest
 */
export class GetLobbyConfigRequest extends Message<GetLobbyConfigRequest> {
  constructor(data?: PartialMessage<GetLobbyConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetLobbyConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbyConfigRequest {
    return new GetLobbyConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbyConfigRequest | PlainMessage<GetLobbyConfigRequest> | undefined, b: GetLobbyConfigRequest | PlainMessage<GetLobbyConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbyConfigRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbyConfigResponse
 */
export class LobbyConfigResponse extends Message<LobbyConfigResponse> {
  /**
   * @generated from field: string version = 1;
   */
  version = "";

  /**
   * @generated from field: string configs = 2;
   */
  configs = "";

  constructor(data?: PartialMessage<LobbyConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbyConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "configs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbyConfigResponse {
    return new LobbyConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbyConfigResponse | PlainMessage<LobbyConfigResponse> | undefined, b: LobbyConfigResponse | PlainMessage<LobbyConfigResponse> | undefined): boolean {
    return proto3.util.equals(LobbyConfigResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetLobbySplashRequest
 */
export class GetLobbySplashRequest extends Message<GetLobbySplashRequest> {
  constructor(data?: PartialMessage<GetLobbySplashRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetLobbySplashRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLobbySplashRequest {
    return new GetLobbySplashRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetLobbySplashRequest | PlainMessage<GetLobbySplashRequest> | undefined, b: GetLobbySplashRequest | PlainMessage<GetLobbySplashRequest> | undefined): boolean {
    return proto3.util.equals(GetLobbySplashRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbySplash
 */
export class LobbySplash extends Message<LobbySplash> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  /**
   * @generated from field: string image_url = 4;
   */
  imageUrl = "";

  /**
   * @generated from field: string link_url = 5;
   */
  linkUrl = "";

  /**
   * @generated from field: int32 daily_limit = 6;
   */
  dailyLimit = 0;

  /**
   * @generated from field: int32 priority = 7;
   */
  priority = 0;

  constructor(data?: PartialMessage<LobbySplash>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbySplash";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "link_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "daily_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "priority", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbySplash {
    return new LobbySplash().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbySplash {
    return new LobbySplash().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbySplash {
    return new LobbySplash().fromJsonString(jsonString, options);
  }

  static equals(a: LobbySplash | PlainMessage<LobbySplash> | undefined, b: LobbySplash | PlainMessage<LobbySplash> | undefined): boolean {
    return proto3.util.equals(LobbySplash, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LobbySplashResponse
 */
export class LobbySplashResponse extends Message<LobbySplashResponse> {
  /**
   * @generated from field: rockgame.lobby.LobbySplash splash = 1;
   */
  splash?: LobbySplash;

  constructor(data?: PartialMessage<LobbySplashResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LobbySplashResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "splash", kind: "message", T: LobbySplash },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LobbySplashResponse {
    return new LobbySplashResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LobbySplashResponse | PlainMessage<LobbySplashResponse> | undefined, b: LobbySplashResponse | PlainMessage<LobbySplashResponse> | undefined): boolean {
    return proto3.util.equals(LobbySplashResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LaunchSelfGameRequest
 */
export class LaunchSelfGameRequest extends Message<LaunchSelfGameRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<LaunchSelfGameRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LaunchSelfGameRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchSelfGameRequest | PlainMessage<LaunchSelfGameRequest> | undefined, b: LaunchSelfGameRequest | PlainMessage<LaunchSelfGameRequest> | undefined): boolean {
    return proto3.util.equals(LaunchSelfGameRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.LaunchSelfGameResponse
 */
export class LaunchSelfGameResponse extends Message<LaunchSelfGameResponse> {
  /**
   * @generated from field: string game_type = 1;
   */
  gameType = "";

  /**
   * @generated from field: string launch_url = 2;
   */
  launchUrl = "";

  /**
   * @generated from field: string session_token = 3;
   */
  sessionToken = "";

  /**
   * @generated from field: string game_id = 4;
   */
  gameId = "";

  /**
   * @generated from field: int64 game_info_id = 5;
   */
  gameInfoId = protoInt64.zero;

  constructor(data?: PartialMessage<LaunchSelfGameResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.LaunchSelfGameResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "launch_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "session_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "game_info_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchSelfGameResponse | PlainMessage<LaunchSelfGameResponse> | undefined, b: LaunchSelfGameResponse | PlainMessage<LaunchSelfGameResponse> | undefined): boolean {
    return proto3.util.equals(LaunchSelfGameResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.GetReddotStateRequest
 */
export class GetReddotStateRequest extends Message<GetReddotStateRequest> {
  constructor(data?: PartialMessage<GetReddotStateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.GetReddotStateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetReddotStateRequest | PlainMessage<GetReddotStateRequest> | undefined, b: GetReddotStateRequest | PlainMessage<GetReddotStateRequest> | undefined): boolean {
    return proto3.util.equals(GetReddotStateRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.ReddotStateResponse
 */
export class ReddotStateResponse extends Message<ReddotStateResponse> {
  /**
   * @generated from field: map<string, int32> categories = 1;
   */
  categories: { [key: string]: number } = {};

  /**
   * @generated from field: int32 total = 2;
   */
  total = 0;

  constructor(data?: PartialMessage<ReddotStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.ReddotStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "categories", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 5 /* ScalarType.INT32 */} },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReddotStateResponse | PlainMessage<ReddotStateResponse> | undefined, b: ReddotStateResponse | PlainMessage<ReddotStateResponse> | undefined): boolean {
    return proto3.util.equals(ReddotStateResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.MarkReddotReadRequest
 */
export class MarkReddotReadRequest extends Message<MarkReddotReadRequest> {
  /**
   * @generated from field: string category = 1;
   */
  category = "";

  constructor(data?: PartialMessage<MarkReddotReadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.MarkReddotReadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MarkReddotReadRequest | PlainMessage<MarkReddotReadRequest> | undefined, b: MarkReddotReadRequest | PlainMessage<MarkReddotReadRequest> | undefined): boolean {
    return proto3.util.equals(MarkReddotReadRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobby.MarkReddotReadResponse
 */
export class MarkReddotReadResponse extends Message<MarkReddotReadResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  constructor(data?: PartialMessage<MarkReddotReadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobby.MarkReddotReadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MarkReddotReadResponse | PlainMessage<MarkReddotReadResponse> | undefined, b: MarkReddotReadResponse | PlainMessage<MarkReddotReadResponse> | undefined): boolean {
    return proto3.util.equals(MarkReddotReadResponse, a, b);
  }
}

