// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file lobby.proto (package rockgame.lobbysession, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.lobbysession.LaunchSelfGameRequest
 */
export class LaunchSelfGameRequest extends Message<LaunchSelfGameRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<LaunchSelfGameRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.LaunchSelfGameRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchSelfGameRequest {
    return new LaunchSelfGameRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchSelfGameRequest | PlainMessage<LaunchSelfGameRequest> | undefined, b: LaunchSelfGameRequest | PlainMessage<LaunchSelfGameRequest> | undefined): boolean {
    return proto3.util.equals(LaunchSelfGameRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.LaunchSelfGameResponse
 */
export class LaunchSelfGameResponse extends Message<LaunchSelfGameResponse> {
  /**
   * @generated from field: string game_type = 1;
   */
  gameType = "";

  /**
   * @generated from field: string launch_url = 2;
   */
  launchUrl = "";

  /**
   * @generated from field: string session_token = 3;
   */
  sessionToken = "";

  /**
   * @generated from field: string game_id = 4;
   */
  gameId = "";

  /**
   * @generated from field: int64 game_info_id = 5;
   */
  gameInfoId = protoInt64.zero;

  constructor(data?: PartialMessage<LaunchSelfGameResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.LaunchSelfGameResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "launch_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "session_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "game_info_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchSelfGameResponse {
    return new LaunchSelfGameResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchSelfGameResponse | PlainMessage<LaunchSelfGameResponse> | undefined, b: LaunchSelfGameResponse | PlainMessage<LaunchSelfGameResponse> | undefined): boolean {
    return proto3.util.equals(LaunchSelfGameResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.EndGameSessionRequest
 */
export class EndGameSessionRequest extends Message<EndGameSessionRequest> {
  /**
   * @generated from field: string session_token = 1;
   */
  sessionToken = "";

  constructor(data?: PartialMessage<EndGameSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.EndGameSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EndGameSessionRequest {
    return new EndGameSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EndGameSessionRequest | PlainMessage<EndGameSessionRequest> | undefined, b: EndGameSessionRequest | PlainMessage<EndGameSessionRequest> | undefined): boolean {
    return proto3.util.equals(EndGameSessionRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.EndGameSessionResponse
 */
export class EndGameSessionResponse extends Message<EndGameSessionResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  constructor(data?: PartialMessage<EndGameSessionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.EndGameSessionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EndGameSessionResponse {
    return new EndGameSessionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EndGameSessionResponse | PlainMessage<EndGameSessionResponse> | undefined, b: EndGameSessionResponse | PlainMessage<EndGameSessionResponse> | undefined): boolean {
    return proto3.util.equals(EndGameSessionResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.ToggleFavoriteRequest
 */
export class ToggleFavoriteRequest extends Message<ToggleFavoriteRequest> {
  /**
   * @generated from field: int64 game_id = 1;
   */
  gameId = protoInt64.zero;

  constructor(data?: PartialMessage<ToggleFavoriteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.ToggleFavoriteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleFavoriteRequest {
    return new ToggleFavoriteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ToggleFavoriteRequest | PlainMessage<ToggleFavoriteRequest> | undefined, b: ToggleFavoriteRequest | PlainMessage<ToggleFavoriteRequest> | undefined): boolean {
    return proto3.util.equals(ToggleFavoriteRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.ToggleFavoriteResponse
 */
export class ToggleFavoriteResponse extends Message<ToggleFavoriteResponse> {
  /**
   * @generated from field: int64 game_id = 1;
   */
  gameId = protoInt64.zero;

  /**
   * @generated from field: bool favorited = 2;
   */
  favorited = false;

  constructor(data?: PartialMessage<ToggleFavoriteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.ToggleFavoriteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "game_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "favorited", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleFavoriteResponse {
    return new ToggleFavoriteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ToggleFavoriteResponse | PlainMessage<ToggleFavoriteResponse> | undefined, b: ToggleFavoriteResponse | PlainMessage<ToggleFavoriteResponse> | undefined): boolean {
    return proto3.util.equals(ToggleFavoriteResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GetRecentGamesRequest
 */
export class GetRecentGamesRequest extends Message<GetRecentGamesRequest> {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit = 0;

  constructor(data?: PartialMessage<GetRecentGamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GetRecentGamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRecentGamesRequest {
    return new GetRecentGamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRecentGamesRequest | PlainMessage<GetRecentGamesRequest> | undefined, b: GetRecentGamesRequest | PlainMessage<GetRecentGamesRequest> | undefined): boolean {
    return proto3.util.equals(GetRecentGamesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GameListItem
 */
export class GameListItem extends Message<GameListItem> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string icon = 3;
   */
  icon = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string launch_url = 5;
   */
  launchUrl = "";

  /**
   * @generated from field: int64 category_id = 6;
   */
  categoryId = protoInt64.zero;

  /**
   * @generated from field: int64 vendor_id = 7;
   */
  vendorId = protoInt64.zero;

  /**
   * @generated from field: string game_type = 8;
   */
  gameType = "";

  /**
   * @generated from field: string game_id = 9;
   */
  gameId = "";

  /**
   * @generated from field: int32 hot = 10;
   */
  hot = 0;

  /**
   * @generated from field: int32 is_new = 11;
   */
  isNew = 0;

  /**
   * @generated from field: int32 sort_order = 12;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<GameListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GameListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "launch_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "category_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "vendor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "hot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "is_new", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameListItem {
    return new GameListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameListItem {
    return new GameListItem().fromJsonString(jsonString, options);
  }

  static equals(a: GameListItem | PlainMessage<GameListItem> | undefined, b: GameListItem | PlainMessage<GameListItem> | undefined): boolean {
    return proto3.util.equals(GameListItem, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.RecentGamesResponse
 */
export class RecentGamesResponse extends Message<RecentGamesResponse> {
  /**
   * @generated from field: repeated rockgame.lobbysession.GameListItem list = 1;
   */
  list: GameListItem[] = [];

  constructor(data?: PartialMessage<RecentGamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.RecentGamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameListItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecentGamesResponse {
    return new RecentGamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RecentGamesResponse | PlainMessage<RecentGamesResponse> | undefined, b: RecentGamesResponse | PlainMessage<RecentGamesResponse> | undefined): boolean {
    return proto3.util.equals(RecentGamesResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GetGameHistoryRequest
 */
export class GetGameHistoryRequest extends Message<GetGameHistoryRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: int32 page = 2;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<GetGameHistoryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GetGameHistoryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGameHistoryRequest {
    return new GetGameHistoryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGameHistoryRequest | PlainMessage<GetGameHistoryRequest> | undefined, b: GetGameHistoryRequest | PlainMessage<GetGameHistoryRequest> | undefined): boolean {
    return proto3.util.equals(GetGameHistoryRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GameHistoryItem
 */
export class GameHistoryItem extends Message<GameHistoryItem> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string game_type = 2;
   */
  gameType = "";

  /**
   * @generated from field: string game_id = 3;
   */
  gameId = "";

  /**
   * @generated from field: int64 bet_amount = 4;
   */
  betAmount = protoInt64.zero;

  /**
   * @generated from field: int64 win_amount = 5;
   */
  winAmount = protoInt64.zero;

  /**
   * @generated from field: int64 net = 6;
   */
  net = protoInt64.zero;

  /**
   * @generated from field: string status = 7;
   */
  status = "";

  /**
   * @generated from field: bool is_free_spin = 8;
   */
  isFreeSpin = false;

  /**
   * @generated from field: int32 duration = 9;
   */
  duration = 0;

  /**
   * @generated from field: repeated int64 player_ids = 10;
   */
  playerIds: bigint[] = [];

  /**
   * @generated from field: int64 winner_id = 11;
   */
  winnerId = protoInt64.zero;

  /**
   * @generated from field: string hand_rank = 12;
   */
  handRank = "";

  /**
   * @generated from field: int64 rake = 13;
   */
  rake = protoInt64.zero;

  /**
   * @generated from field: string created_at = 14;
   */
  createdAt = "";

  constructor(data?: PartialMessage<GameHistoryItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GameHistoryItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "bet_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "win_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "net", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "is_free_spin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "duration", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "player_ids", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
    { no: 11, name: "winner_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "hand_rank", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "rake", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 14, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameHistoryItem {
    return new GameHistoryItem().fromJsonString(jsonString, options);
  }

  static equals(a: GameHistoryItem | PlainMessage<GameHistoryItem> | undefined, b: GameHistoryItem | PlainMessage<GameHistoryItem> | undefined): boolean {
    return proto3.util.equals(GameHistoryItem, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GameHistoryResponse
 */
export class GameHistoryResponse extends Message<GameHistoryResponse> {
  /**
   * @generated from field: repeated rockgame.lobbysession.GameHistoryItem list = 1;
   */
  list: GameHistoryItem[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: bool has_more = 5;
   */
  hasMore = false;

  constructor(data?: PartialMessage<GameHistoryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GameHistoryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: GameHistoryItem, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "has_more", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameHistoryResponse {
    return new GameHistoryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GameHistoryResponse | PlainMessage<GameHistoryResponse> | undefined, b: GameHistoryResponse | PlainMessage<GameHistoryResponse> | undefined): boolean {
    return proto3.util.equals(GameHistoryResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.GetReddotStateRequest
 */
export class GetReddotStateRequest extends Message<GetReddotStateRequest> {
  constructor(data?: PartialMessage<GetReddotStateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.GetReddotStateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReddotStateRequest {
    return new GetReddotStateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetReddotStateRequest | PlainMessage<GetReddotStateRequest> | undefined, b: GetReddotStateRequest | PlainMessage<GetReddotStateRequest> | undefined): boolean {
    return proto3.util.equals(GetReddotStateRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.ReddotStateResponse
 */
export class ReddotStateResponse extends Message<ReddotStateResponse> {
  /**
   * @generated from field: map<string, int32> categories = 1;
   */
  categories: { [key: string]: number } = {};

  /**
   * @generated from field: int32 total = 2;
   */
  total = 0;

  constructor(data?: PartialMessage<ReddotStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.ReddotStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "categories", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 5 /* ScalarType.INT32 */} },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReddotStateResponse {
    return new ReddotStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReddotStateResponse | PlainMessage<ReddotStateResponse> | undefined, b: ReddotStateResponse | PlainMessage<ReddotStateResponse> | undefined): boolean {
    return proto3.util.equals(ReddotStateResponse, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.MarkReddotReadRequest
 */
export class MarkReddotReadRequest extends Message<MarkReddotReadRequest> {
  /**
   * @generated from field: string category = 1;
   */
  category = "";

  constructor(data?: PartialMessage<MarkReddotReadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.MarkReddotReadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkReddotReadRequest {
    return new MarkReddotReadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MarkReddotReadRequest | PlainMessage<MarkReddotReadRequest> | undefined, b: MarkReddotReadRequest | PlainMessage<MarkReddotReadRequest> | undefined): boolean {
    return proto3.util.equals(MarkReddotReadRequest, a, b);
  }
}

/**
 * @generated from message rockgame.lobbysession.MarkReddotReadResponse
 */
export class MarkReddotReadResponse extends Message<MarkReddotReadResponse> {
  /**
   * @generated from field: string status = 1;
   */
  status = "";

  constructor(data?: PartialMessage<MarkReddotReadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.lobbysession.MarkReddotReadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkReddotReadResponse {
    return new MarkReddotReadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MarkReddotReadResponse | PlainMessage<MarkReddotReadResponse> | undefined, b: MarkReddotReadResponse | PlainMessage<MarkReddotReadResponse> | undefined): boolean {
    return proto3.util.equals(MarkReddotReadResponse, a, b);
  }
}
