// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file lobby.proto (package rockgame.lobby, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EndGameSessionRequest, EndGameSessionResponse, GameHistoryResponse, GameListResponse, GameVendorsResponse, GetGameHistoryRequest, GetGameListRequest, GetGameVendorsRequest, GetLobbyBannersRequest, GetLobbyCategoriesRequest, GetLobbyConfigRequest, GetLobbyGamesRequest, GetLobbySplashRequest, GetRecentGamesRequest, GetReddotStateRequest, LaunchSelfGameRequest, LaunchSelfGameResponse, LobbyBannersResponse, LobbyCategoriesResponse, LobbyConfigResponse, LobbyGamesResponse, LobbySplashResponse, MarkReddotReadRequest, MarkReddotReadResponse, RecentGamesResponse, ReddotStateResponse, SearchGamesRequest, SearchGamesResponse, ToggleFavoriteRequest, ToggleFavoriteResponse } from "./lobby_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * LobbyService handles lobby display and game launch operations.
 * Implemented by lobby-node.
 *
 * @generated from service rockgame.lobby.LobbyService
 */
export const LobbyService = {
  typeName: "rockgame.lobby.LobbyService",
  methods: {
    /**
     * GetLobbyBanners returns active lobby banners.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetLobbyBanners
     */
    getLobbyBanners: {
      name: "GetLobbyBanners",
      I: GetLobbyBannersRequest,
      O: LobbyBannersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLobbyCategories returns game categories with game counts.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetLobbyCategories
     */
    getLobbyCategories: {
      name: "GetLobbyCategories",
      I: GetLobbyCategoriesRequest,
      O: LobbyCategoriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLobbyGames returns paginated game list.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetLobbyGames
     */
    getLobbyGames: {
      name: "GetLobbyGames",
      I: GetLobbyGamesRequest,
      O: LobbyGamesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLobbyConfig returns lobby configuration.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetLobbyConfig
     */
    getLobbyConfig: {
      name: "GetLobbyConfig",
      I: GetLobbyConfigRequest,
      O: LobbyConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLobbySplash returns active splash popup.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetLobbySplash
     */
    getLobbySplash: {
      name: "GetLobbySplash",
      I: GetLobbySplashRequest,
      O: LobbySplashResponse,
      kind: MethodKind.Unary,
    },
    /**
     * LaunchSelfGame launches a self-hosted game.
     *
     * @generated from rpc rockgame.lobby.LobbyService.LaunchSelfGame
     */
    launchSelfGame: {
      name: "LaunchSelfGame",
      I: LaunchSelfGameRequest,
      O: LaunchSelfGameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGameVendors returns all active game vendors.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetGameVendors
     */
    getGameVendors: {
      name: "GetGameVendors",
      I: GetGameVendorsRequest,
      O: GameVendorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGameList returns paginated, filterable game list.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetGameList
     */
    getGameList: {
      name: "GetGameList",
      I: GetGameListRequest,
      O: GameListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SearchGames searches games by keyword.
     *
     * @generated from rpc rockgame.lobby.LobbyService.SearchGames
     */
    searchGames: {
      name: "SearchGames",
      I: SearchGamesRequest,
      O: SearchGamesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ToggleFavorite adds or removes a game from user favorites.
     *
     * @generated from rpc rockgame.lobby.LobbyService.ToggleFavorite
     */
    toggleFavorite: {
      name: "ToggleFavorite",
      I: ToggleFavoriteRequest,
      O: ToggleFavoriteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetRecentGames returns the user's recently played games.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetRecentGames
     */
    getRecentGames: {
      name: "GetRecentGames",
      I: GetRecentGamesRequest,
      O: RecentGamesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGameHistory returns the user's game round history.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetGameHistory
     */
    getGameHistory: {
      name: "GetGameHistory",
      I: GetGameHistoryRequest,
      O: GameHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * EndGameSession ends a game session.
     *
     * @generated from rpc rockgame.lobby.LobbyService.EndGameSession
     */
    endGameSession: {
      name: "EndGameSession",
      I: EndGameSessionRequest,
      O: EndGameSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetReddotState returns unread notification counts.
     *
     * @generated from rpc rockgame.lobby.LobbyService.GetReddotState
     */
    getReddotState: {
      name: "GetReddotState",
      I: GetReddotStateRequest,
      O: ReddotStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * MarkReddotRead marks notifications as read.
     *
     * @generated from rpc rockgame.lobby.LobbyService.MarkReddotRead
     */
    markReddotRead: {
      name: "MarkReddotRead",
      I: MarkReddotReadRequest,
      O: MarkReddotReadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

