// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file rank.proto (package rockgame.rank, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMyRankRequest, GetRankListRequest, GetRankSnapshotRequest, GetTopRanksRequest, MyRankResponse, RankListResponse, RankSnapshotResponse, TopRanksResponse } from "./rank_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * RankService handles leaderboard and ranking operations.
 * Implemented by rank-mesh.
 *
 * @generated from service rockgame.rank.RankService
 */
export const RankService = {
  typeName: "rockgame.rank.RankService",
  methods: {
    /**
     * @generated from rpc rockgame.rank.RankService.GetRankList
     */
    getRankList: {
      name: "GetRankList",
      I: GetRankListRequest,
      O: RankListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.rank.RankService.GetMyRank
     */
    getMyRank: {
      name: "GetMyRank",
      I: GetMyRankRequest,
      O: MyRankResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.rank.RankService.GetTopRanks
     */
    getTopRanks: {
      name: "GetTopRanks",
      I: GetTopRanksRequest,
      O: TopRanksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.rank.RankService.GetRankSnapshot
     */
    getRankSnapshot: {
      name: "GetRankSnapshot",
      I: GetRankSnapshotRequest,
      O: RankSnapshotResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

