// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file rank.proto (package rockgame.rank, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.rank.GetRankListRequest
 */
export class GetRankListRequest extends Message<GetRankListRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string period = 2;
   */
  period = "";

  /**
   * @generated from field: int32 page = 3;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<GetRankListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.GetRankListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRankListRequest {
    return new GetRankListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRankListRequest {
    return new GetRankListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRankListRequest {
    return new GetRankListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRankListRequest | PlainMessage<GetRankListRequest> | undefined, b: GetRankListRequest | PlainMessage<GetRankListRequest> | undefined): boolean {
    return proto3.util.equals(GetRankListRequest, a, b);
  }
}

/**
 * @generated from message rockgame.rank.RankEntry
 */
export class RankEntry extends Message<RankEntry> {
  /**
   * @generated from field: int32 rank = 1;
   */
  rank = 0;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname = "";

  /**
   * @generated from field: int64 score = 4;
   */
  score = protoInt64.zero;

  /**
   * @generated from field: string avatar = 5;
   */
  avatar = "";

  constructor(data?: PartialMessage<RankEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.RankEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "rank", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "nickname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "score", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "avatar", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankEntry {
    return new RankEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankEntry {
    return new RankEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankEntry {
    return new RankEntry().fromJsonString(jsonString, options);
  }

  static equals(a: RankEntry | PlainMessage<RankEntry> | undefined, b: RankEntry | PlainMessage<RankEntry> | undefined): boolean {
    return proto3.util.equals(RankEntry, a, b);
  }
}

/**
 * @generated from message rockgame.rank.RankListResponse
 */
export class RankListResponse extends Message<RankListResponse> {
  /**
   * @generated from field: repeated rockgame.rank.RankEntry entries = 1;
   */
  entries: RankEntry[] = [];

  /**
   * @generated from field: int32 total = 2;
   */
  total = 0;

  constructor(data?: PartialMessage<RankListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.RankListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entries", kind: "message", T: RankEntry, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankListResponse {
    return new RankListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankListResponse {
    return new RankListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankListResponse {
    return new RankListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RankListResponse | PlainMessage<RankListResponse> | undefined, b: RankListResponse | PlainMessage<RankListResponse> | undefined): boolean {
    return proto3.util.equals(RankListResponse, a, b);
  }
}

/**
 * @generated from message rockgame.rank.GetMyRankRequest
 */
export class GetMyRankRequest extends Message<GetMyRankRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string period = 2;
   */
  period = "";

  constructor(data?: PartialMessage<GetMyRankRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.GetMyRankRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMyRankRequest {
    return new GetMyRankRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMyRankRequest {
    return new GetMyRankRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMyRankRequest {
    return new GetMyRankRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMyRankRequest | PlainMessage<GetMyRankRequest> | undefined, b: GetMyRankRequest | PlainMessage<GetMyRankRequest> | undefined): boolean {
    return proto3.util.equals(GetMyRankRequest, a, b);
  }
}

/**
 * @generated from message rockgame.rank.MyRankResponse
 */
export class MyRankResponse extends Message<MyRankResponse> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int32 rank = 2;
   */
  rank = 0;

  /**
   * @generated from field: int64 score = 3;
   */
  score = protoInt64.zero;

  /**
   * @generated from field: int32 total_users = 4;
   */
  totalUsers = 0;

  constructor(data?: PartialMessage<MyRankResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.MyRankResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "rank", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "score", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_users", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MyRankResponse {
    return new MyRankResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MyRankResponse {
    return new MyRankResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MyRankResponse {
    return new MyRankResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MyRankResponse | PlainMessage<MyRankResponse> | undefined, b: MyRankResponse | PlainMessage<MyRankResponse> | undefined): boolean {
    return proto3.util.equals(MyRankResponse, a, b);
  }
}

/**
 * @generated from message rockgame.rank.GetTopRanksRequest
 */
export class GetTopRanksRequest extends Message<GetTopRanksRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string period = 2;
   */
  period = "";

  /**
   * @generated from field: int32 limit = 3;
   */
  limit = 0;

  constructor(data?: PartialMessage<GetTopRanksRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.GetTopRanksRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTopRanksRequest {
    return new GetTopRanksRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTopRanksRequest {
    return new GetTopRanksRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTopRanksRequest {
    return new GetTopRanksRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTopRanksRequest | PlainMessage<GetTopRanksRequest> | undefined, b: GetTopRanksRequest | PlainMessage<GetTopRanksRequest> | undefined): boolean {
    return proto3.util.equals(GetTopRanksRequest, a, b);
  }
}

/**
 * @generated from message rockgame.rank.TopRanksResponse
 */
export class TopRanksResponse extends Message<TopRanksResponse> {
  /**
   * @generated from field: repeated rockgame.rank.RankEntry entries = 1;
   */
  entries: RankEntry[] = [];

  constructor(data?: PartialMessage<TopRanksResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.TopRanksResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entries", kind: "message", T: RankEntry, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TopRanksResponse {
    return new TopRanksResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TopRanksResponse {
    return new TopRanksResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TopRanksResponse {
    return new TopRanksResponse().fromJsonString(jsonString, options);
  }

  static equals(a: TopRanksResponse | PlainMessage<TopRanksResponse> | undefined, b: TopRanksResponse | PlainMessage<TopRanksResponse> | undefined): boolean {
    return proto3.util.equals(TopRanksResponse, a, b);
  }
}

/**
 * @generated from message rockgame.rank.GetRankSnapshotRequest
 */
export class GetRankSnapshotRequest extends Message<GetRankSnapshotRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string period = 2;
   */
  period = "";

  constructor(data?: PartialMessage<GetRankSnapshotRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.GetRankSnapshotRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRankSnapshotRequest {
    return new GetRankSnapshotRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRankSnapshotRequest {
    return new GetRankSnapshotRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRankSnapshotRequest {
    return new GetRankSnapshotRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRankSnapshotRequest | PlainMessage<GetRankSnapshotRequest> | undefined, b: GetRankSnapshotRequest | PlainMessage<GetRankSnapshotRequest> | undefined): boolean {
    return proto3.util.equals(GetRankSnapshotRequest, a, b);
  }
}

/**
 * @generated from message rockgame.rank.RankSnapshotResponse
 */
export class RankSnapshotResponse extends Message<RankSnapshotResponse> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: string created_at = 2;
   */
  createdAt = "";

  /**
   * @generated from field: repeated rockgame.rank.RankEntry entries = 3;
   */
  entries: RankEntry[] = [];

  constructor(data?: PartialMessage<RankSnapshotResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.rank.RankSnapshotResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "entries", kind: "message", T: RankEntry, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankSnapshotResponse {
    return new RankSnapshotResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankSnapshotResponse {
    return new RankSnapshotResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankSnapshotResponse {
    return new RankSnapshotResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RankSnapshotResponse | PlainMessage<RankSnapshotResponse> | undefined, b: RankSnapshotResponse | PlainMessage<RankSnapshotResponse> | undefined): boolean {
    return proto3.util.equals(RankSnapshotResponse, a, b);
  }
}

