// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file shop.proto (package rockgame.shop, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminApproveWithdrawRequest, AdminApproveWithdrawResponse, AdminConfirmRechargeRequest, AdminConfirmRechargeResponse, AdminMarkWithdrawPaidRequest, AdminMarkWithdrawPaidResponse, AdminRejectWithdrawRequest, AdminRejectWithdrawResponse, AmountOptionsResponse, ClaimRechargeBonusRequest, ClaimRechargeBonusResponse, CreateRechargeRequest, CreateRechargeResponse, CreateWithdrawRequest, CreateWithdrawResponse, GetDepositAmountOptionsRequest, GetDepositProductsRequest, GetOrdersRequest, GetPaymentAccountsRequest, GetPaymentChannelsRequest, GetPaymentMethodsRequest, GetShopWalletRequest, GetWithdrawAmountOptionsRequest, GetWithdrawChannelsRequest, GetWithdrawMethodsRequest, GetWithdrawProductsRequest, OrdersResponse, PaymentAccountsResponse, PaymentChannelsResponse, PaymentMethodsResponse, SavePaymentAccountRequest, SavePaymentAccountResponse, SetWithdrawPasswordRequest, SetWithdrawPasswordResponse, ShopProductsResponse, ShopWalletResponse, WithdrawChannelsResponse } from "./shop_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ShopService handles recharge, withdraw, and payment operations.
 * Implemented by shop-mesh.
 *
 * @generated from service rockgame.shop.ShopService
 */
export const ShopService = {
  typeName: "rockgame.shop.ShopService",
  methods: {
    /**
     * @generated from rpc rockgame.shop.ShopService.GetShopWallet
     */
    getShopWallet: {
      name: "GetShopWallet",
      I: GetShopWalletRequest,
      O: ShopWalletResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetPaymentChannels
     */
    getPaymentChannels: {
      name: "GetPaymentChannels",
      I: GetPaymentChannelsRequest,
      O: PaymentChannelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetWithdrawChannels
     */
    getWithdrawChannels: {
      name: "GetWithdrawChannels",
      I: GetWithdrawChannelsRequest,
      O: WithdrawChannelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.CreateRecharge
     */
    createRecharge: {
      name: "CreateRecharge",
      I: CreateRechargeRequest,
      O: CreateRechargeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.CreateWithdraw
     */
    createWithdraw: {
      name: "CreateWithdraw",
      I: CreateWithdrawRequest,
      O: CreateWithdrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetOrders
     */
    getOrders: {
      name: "GetOrders",
      I: GetOrdersRequest,
      O: OrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetPaymentAccounts
     */
    getPaymentAccounts: {
      name: "GetPaymentAccounts",
      I: GetPaymentAccountsRequest,
      O: PaymentAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.SavePaymentAccount
     */
    savePaymentAccount: {
      name: "SavePaymentAccount",
      I: SavePaymentAccountRequest,
      O: SavePaymentAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.SetWithdrawPassword
     */
    setWithdrawPassword: {
      name: "SetWithdrawPassword",
      I: SetWithdrawPasswordRequest,
      O: SetWithdrawPasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Admin management RPCs — called by admin-node via gRPC.
     *
     * @generated from rpc rockgame.shop.ShopService.AdminApproveWithdraw
     */
    adminApproveWithdraw: {
      name: "AdminApproveWithdraw",
      I: AdminApproveWithdrawRequest,
      O: AdminApproveWithdrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.AdminRejectWithdraw
     */
    adminRejectWithdraw: {
      name: "AdminRejectWithdraw",
      I: AdminRejectWithdrawRequest,
      O: AdminRejectWithdrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.AdminMarkWithdrawPaid
     */
    adminMarkWithdrawPaid: {
      name: "AdminMarkWithdrawPaid",
      I: AdminMarkWithdrawPaidRequest,
      O: AdminMarkWithdrawPaidResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.AdminConfirmRecharge
     */
    adminConfirmRecharge: {
      name: "AdminConfirmRecharge",
      I: AdminConfirmRechargeRequest,
      O: AdminConfirmRechargeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ClaimRechargeBonus records a recharge bonus claim for activity service.
     *
     * @generated from rpc rockgame.shop.ShopService.ClaimRechargeBonus
     */
    claimRechargeBonus: {
      name: "ClaimRechargeBonus",
      I: ClaimRechargeBonusRequest,
      O: ClaimRechargeBonusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Payment methods (grouped with channels, VIP/label filtered)
     *
     * @generated from rpc rockgame.shop.ShopService.GetPaymentMethods
     */
    getPaymentMethods: {
      name: "GetPaymentMethods",
      I: GetPaymentMethodsRequest,
      O: PaymentMethodsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetWithdrawMethods
     */
    getWithdrawMethods: {
      name: "GetWithdrawMethods",
      I: GetWithdrawMethodsRequest,
      O: PaymentMethodsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Amount preset options (per-label filtering)
     *
     * @generated from rpc rockgame.shop.ShopService.GetDepositAmountOptions
     */
    getDepositAmountOptions: {
      name: "GetDepositAmountOptions",
      I: GetDepositAmountOptionsRequest,
      O: AmountOptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetWithdrawAmountOptions
     */
    getWithdrawAmountOptions: {
      name: "GetWithdrawAmountOptions",
      I: GetWithdrawAmountOptionsRequest,
      O: AmountOptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Shop products (deposit/withdraw amount options with bonus)
     *
     * @generated from rpc rockgame.shop.ShopService.GetDepositProducts
     */
    getDepositProducts: {
      name: "GetDepositProducts",
      I: GetDepositProductsRequest,
      O: ShopProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.shop.ShopService.GetWithdrawProducts
     */
    getWithdrawProducts: {
      name: "GetWithdrawProducts",
      I: GetWithdrawProductsRequest,
      O: ShopProductsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

