// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file shop.proto (package rockgame.shop, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.shop.GetShopWalletRequest
 */
export class GetShopWalletRequest extends Message<GetShopWalletRequest> {
  constructor(data?: PartialMessage<GetShopWalletRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetShopWalletRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShopWalletRequest {
    return new GetShopWalletRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShopWalletRequest {
    return new GetShopWalletRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShopWalletRequest {
    return new GetShopWalletRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetShopWalletRequest | PlainMessage<GetShopWalletRequest> | undefined, b: GetShopWalletRequest | PlainMessage<GetShopWalletRequest> | undefined): boolean {
    return proto3.util.equals(GetShopWalletRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.ShopWalletResponse
 */
export class ShopWalletResponse extends Message<ShopWalletResponse> {
  /**
   * @generated from field: int64 cash_balance = 1;
   */
  cashBalance = protoInt64.zero;

  /**
   * @generated from field: int64 frozen_balance = 2;
   */
  frozenBalance = protoInt64.zero;

  /**
   * @generated from field: int64 total_recharge = 3;
   */
  totalRecharge = protoInt64.zero;

  /**
   * @generated from field: int64 total_withdraw = 4;
   */
  totalWithdraw = protoInt64.zero;

  constructor(data?: PartialMessage<ShopWalletResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.ShopWalletResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cash_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "frozen_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "total_recharge", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_withdraw", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShopWalletResponse {
    return new ShopWalletResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShopWalletResponse {
    return new ShopWalletResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShopWalletResponse {
    return new ShopWalletResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ShopWalletResponse | PlainMessage<ShopWalletResponse> | undefined, b: ShopWalletResponse | PlainMessage<ShopWalletResponse> | undefined): boolean {
    return proto3.util.equals(ShopWalletResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetPaymentChannelsRequest
 */
export class GetPaymentChannelsRequest extends Message<GetPaymentChannelsRequest> {
  constructor(data?: PartialMessage<GetPaymentChannelsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetPaymentChannelsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPaymentChannelsRequest {
    return new GetPaymentChannelsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPaymentChannelsRequest {
    return new GetPaymentChannelsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPaymentChannelsRequest {
    return new GetPaymentChannelsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPaymentChannelsRequest | PlainMessage<GetPaymentChannelsRequest> | undefined, b: GetPaymentChannelsRequest | PlainMessage<GetPaymentChannelsRequest> | undefined): boolean {
    return proto3.util.equals(GetPaymentChannelsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentChannel
 */
export class PaymentChannel extends Message<PaymentChannel> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string type = 3;
   */
  type = "";

  /**
   * @generated from field: int64 min_amount = 4;
   */
  minAmount = protoInt64.zero;

  /**
   * @generated from field: int64 max_amount = 5;
   */
  maxAmount = protoInt64.zero;

  /**
   * @generated from field: int64 fee_rate = 6;
   */
  feeRate = protoInt64.zero;

  constructor(data?: PartialMessage<PaymentChannel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentChannel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "min_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "max_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "fee_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentChannel {
    return new PaymentChannel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentChannel {
    return new PaymentChannel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentChannel {
    return new PaymentChannel().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentChannel | PlainMessage<PaymentChannel> | undefined, b: PaymentChannel | PlainMessage<PaymentChannel> | undefined): boolean {
    return proto3.util.equals(PaymentChannel, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentChannelsResponse
 */
export class PaymentChannelsResponse extends Message<PaymentChannelsResponse> {
  /**
   * @generated from field: repeated rockgame.shop.PaymentChannel channels = 1;
   */
  channels: PaymentChannel[] = [];

  constructor(data?: PartialMessage<PaymentChannelsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentChannelsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channels", kind: "message", T: PaymentChannel, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentChannelsResponse {
    return new PaymentChannelsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentChannelsResponse {
    return new PaymentChannelsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentChannelsResponse {
    return new PaymentChannelsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentChannelsResponse | PlainMessage<PaymentChannelsResponse> | undefined, b: PaymentChannelsResponse | PlainMessage<PaymentChannelsResponse> | undefined): boolean {
    return proto3.util.equals(PaymentChannelsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetWithdrawChannelsRequest
 */
export class GetWithdrawChannelsRequest extends Message<GetWithdrawChannelsRequest> {
  constructor(data?: PartialMessage<GetWithdrawChannelsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetWithdrawChannelsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWithdrawChannelsRequest {
    return new GetWithdrawChannelsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWithdrawChannelsRequest {
    return new GetWithdrawChannelsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWithdrawChannelsRequest {
    return new GetWithdrawChannelsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWithdrawChannelsRequest | PlainMessage<GetWithdrawChannelsRequest> | undefined, b: GetWithdrawChannelsRequest | PlainMessage<GetWithdrawChannelsRequest> | undefined): boolean {
    return proto3.util.equals(GetWithdrawChannelsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.WithdrawChannel
 */
export class WithdrawChannel extends Message<WithdrawChannel> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string type = 3;
   */
  type = "";

  /**
   * @generated from field: int64 min_amount = 4;
   */
  minAmount = protoInt64.zero;

  /**
   * @generated from field: int64 max_amount = 5;
   */
  maxAmount = protoInt64.zero;

  /**
   * @generated from field: int64 fee_rate = 6;
   */
  feeRate = protoInt64.zero;

  constructor(data?: PartialMessage<WithdrawChannel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.WithdrawChannel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "min_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "max_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "fee_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WithdrawChannel {
    return new WithdrawChannel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WithdrawChannel {
    return new WithdrawChannel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WithdrawChannel {
    return new WithdrawChannel().fromJsonString(jsonString, options);
  }

  static equals(a: WithdrawChannel | PlainMessage<WithdrawChannel> | undefined, b: WithdrawChannel | PlainMessage<WithdrawChannel> | undefined): boolean {
    return proto3.util.equals(WithdrawChannel, a, b);
  }
}

/**
 * @generated from message rockgame.shop.WithdrawChannelsResponse
 */
export class WithdrawChannelsResponse extends Message<WithdrawChannelsResponse> {
  /**
   * @generated from field: repeated rockgame.shop.WithdrawChannel channels = 1;
   */
  channels: WithdrawChannel[] = [];

  constructor(data?: PartialMessage<WithdrawChannelsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.WithdrawChannelsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channels", kind: "message", T: WithdrawChannel, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WithdrawChannelsResponse {
    return new WithdrawChannelsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WithdrawChannelsResponse {
    return new WithdrawChannelsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WithdrawChannelsResponse {
    return new WithdrawChannelsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WithdrawChannelsResponse | PlainMessage<WithdrawChannelsResponse> | undefined, b: WithdrawChannelsResponse | PlainMessage<WithdrawChannelsResponse> | undefined): boolean {
    return proto3.util.equals(WithdrawChannelsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.CreateRechargeRequest
 */
export class CreateRechargeRequest extends Message<CreateRechargeRequest> {
  /**
   * @generated from field: int64 channel_id = 1;
   */
  channelId = protoInt64.zero;

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: int64 product_id = 3;
   */
  productId = protoInt64.zero;

  constructor(data?: PartialMessage<CreateRechargeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.CreateRechargeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "product_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRechargeRequest {
    return new CreateRechargeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRechargeRequest {
    return new CreateRechargeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRechargeRequest {
    return new CreateRechargeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRechargeRequest | PlainMessage<CreateRechargeRequest> | undefined, b: CreateRechargeRequest | PlainMessage<CreateRechargeRequest> | undefined): boolean {
    return proto3.util.equals(CreateRechargeRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.CreateRechargeResponse
 */
export class CreateRechargeResponse extends Message<CreateRechargeResponse> {
  /**
   * @generated from field: string order_no = 1;
   */
  orderNo = "";

  /**
   * @generated from field: string pay_url = 2;
   */
  payUrl = "";

  constructor(data?: PartialMessage<CreateRechargeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.CreateRechargeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_no", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pay_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRechargeResponse {
    return new CreateRechargeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRechargeResponse {
    return new CreateRechargeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRechargeResponse {
    return new CreateRechargeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRechargeResponse | PlainMessage<CreateRechargeResponse> | undefined, b: CreateRechargeResponse | PlainMessage<CreateRechargeResponse> | undefined): boolean {
    return proto3.util.equals(CreateRechargeResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.CreateWithdrawRequest
 */
export class CreateWithdrawRequest extends Message<CreateWithdrawRequest> {
  /**
   * @generated from field: int64 channel_id = 1;
   */
  channelId = protoInt64.zero;

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: string account_info = 3;
   */
  accountInfo = "";

  /**
   * @generated from field: string withdraw_password = 4;
   */
  withdrawPassword = "";

  constructor(data?: PartialMessage<CreateWithdrawRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.CreateWithdrawRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "account_info", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "withdraw_password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWithdrawRequest {
    return new CreateWithdrawRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWithdrawRequest {
    return new CreateWithdrawRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWithdrawRequest {
    return new CreateWithdrawRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWithdrawRequest | PlainMessage<CreateWithdrawRequest> | undefined, b: CreateWithdrawRequest | PlainMessage<CreateWithdrawRequest> | undefined): boolean {
    return proto3.util.equals(CreateWithdrawRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.CreateWithdrawResponse
 */
export class CreateWithdrawResponse extends Message<CreateWithdrawResponse> {
  /**
   * @generated from field: string order_no = 1;
   */
  orderNo = "";

  constructor(data?: PartialMessage<CreateWithdrawResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.CreateWithdrawResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_no", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateWithdrawResponse {
    return new CreateWithdrawResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateWithdrawResponse {
    return new CreateWithdrawResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateWithdrawResponse {
    return new CreateWithdrawResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateWithdrawResponse | PlainMessage<CreateWithdrawResponse> | undefined, b: CreateWithdrawResponse | PlainMessage<CreateWithdrawResponse> | undefined): boolean {
    return proto3.util.equals(CreateWithdrawResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetOrdersRequest
 */
export class GetOrdersRequest extends Message<GetOrdersRequest> {
  /**
   * "recharge" or "withdraw"
   *
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: int32 page = 2;
   */
  page = 0;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize = 0;

  constructor(data?: PartialMessage<GetOrdersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetOrdersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOrdersRequest {
    return new GetOrdersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOrdersRequest {
    return new GetOrdersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOrdersRequest {
    return new GetOrdersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetOrdersRequest | PlainMessage<GetOrdersRequest> | undefined, b: GetOrdersRequest | PlainMessage<GetOrdersRequest> | undefined): boolean {
    return proto3.util.equals(GetOrdersRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.Order
 */
export class Order extends Message<Order> {
  /**
   * @generated from field: string order_no = 1;
   */
  orderNo = "";

  /**
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * @generated from field: int64 amount = 3;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: int32 status = 4;
   */
  status = 0;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt = "";

  constructor(data?: PartialMessage<Order>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.Order";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_no", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Order {
    return new Order().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Order {
    return new Order().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Order {
    return new Order().fromJsonString(jsonString, options);
  }

  static equals(a: Order | PlainMessage<Order> | undefined, b: Order | PlainMessage<Order> | undefined): boolean {
    return proto3.util.equals(Order, a, b);
  }
}

/**
 * @generated from message rockgame.shop.OrdersResponse
 */
export class OrdersResponse extends Message<OrdersResponse> {
  /**
   * @generated from field: repeated rockgame.shop.Order orders = 1;
   */
  orders: Order[] = [];

  /**
   * @generated from field: int32 total = 2;
   */
  total = 0;

  constructor(data?: PartialMessage<OrdersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.OrdersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "orders", kind: "message", T: Order, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OrdersResponse {
    return new OrdersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OrdersResponse {
    return new OrdersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OrdersResponse {
    return new OrdersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: OrdersResponse | PlainMessage<OrdersResponse> | undefined, b: OrdersResponse | PlainMessage<OrdersResponse> | undefined): boolean {
    return proto3.util.equals(OrdersResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetPaymentAccountsRequest
 */
export class GetPaymentAccountsRequest extends Message<GetPaymentAccountsRequest> {
  constructor(data?: PartialMessage<GetPaymentAccountsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetPaymentAccountsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPaymentAccountsRequest {
    return new GetPaymentAccountsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPaymentAccountsRequest {
    return new GetPaymentAccountsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPaymentAccountsRequest {
    return new GetPaymentAccountsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPaymentAccountsRequest | PlainMessage<GetPaymentAccountsRequest> | undefined, b: GetPaymentAccountsRequest | PlainMessage<GetPaymentAccountsRequest> | undefined): boolean {
    return proto3.util.equals(GetPaymentAccountsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentAccount
 */
export class PaymentAccount extends Message<PaymentAccount> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string bank_name = 2;
   */
  bankName = "";

  /**
   * @generated from field: string account_number = 3;
   */
  accountNumber = "";

  /**
   * @generated from field: string account_name = 4;
   */
  accountName = "";

  /**
   * @generated from field: string type = 5;
   */
  type = "";

  constructor(data?: PartialMessage<PaymentAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "bank_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "account_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "account_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentAccount {
    return new PaymentAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentAccount {
    return new PaymentAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentAccount {
    return new PaymentAccount().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentAccount | PlainMessage<PaymentAccount> | undefined, b: PaymentAccount | PlainMessage<PaymentAccount> | undefined): boolean {
    return proto3.util.equals(PaymentAccount, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentAccountsResponse
 */
export class PaymentAccountsResponse extends Message<PaymentAccountsResponse> {
  /**
   * @generated from field: repeated rockgame.shop.PaymentAccount accounts = 1;
   */
  accounts: PaymentAccount[] = [];

  constructor(data?: PartialMessage<PaymentAccountsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentAccountsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "accounts", kind: "message", T: PaymentAccount, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentAccountsResponse {
    return new PaymentAccountsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentAccountsResponse {
    return new PaymentAccountsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentAccountsResponse {
    return new PaymentAccountsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentAccountsResponse | PlainMessage<PaymentAccountsResponse> | undefined, b: PaymentAccountsResponse | PlainMessage<PaymentAccountsResponse> | undefined): boolean {
    return proto3.util.equals(PaymentAccountsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.SavePaymentAccountRequest
 */
export class SavePaymentAccountRequest extends Message<SavePaymentAccountRequest> {
  /**
   * @generated from field: string bank_name = 1;
   */
  bankName = "";

  /**
   * @generated from field: string account_number = 2;
   */
  accountNumber = "";

  /**
   * @generated from field: string account_name = 3;
   */
  accountName = "";

  /**
   * @generated from field: string type = 4;
   */
  type = "";

  constructor(data?: PartialMessage<SavePaymentAccountRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.SavePaymentAccountRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bank_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "account_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SavePaymentAccountRequest {
    return new SavePaymentAccountRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SavePaymentAccountRequest {
    return new SavePaymentAccountRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SavePaymentAccountRequest {
    return new SavePaymentAccountRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SavePaymentAccountRequest | PlainMessage<SavePaymentAccountRequest> | undefined, b: SavePaymentAccountRequest | PlainMessage<SavePaymentAccountRequest> | undefined): boolean {
    return proto3.util.equals(SavePaymentAccountRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.SavePaymentAccountResponse
 */
export class SavePaymentAccountResponse extends Message<SavePaymentAccountResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<SavePaymentAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.SavePaymentAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SavePaymentAccountResponse {
    return new SavePaymentAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SavePaymentAccountResponse {
    return new SavePaymentAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SavePaymentAccountResponse {
    return new SavePaymentAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SavePaymentAccountResponse | PlainMessage<SavePaymentAccountResponse> | undefined, b: SavePaymentAccountResponse | PlainMessage<SavePaymentAccountResponse> | undefined): boolean {
    return proto3.util.equals(SavePaymentAccountResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.SetWithdrawPasswordRequest
 */
export class SetWithdrawPasswordRequest extends Message<SetWithdrawPasswordRequest> {
  /**
   * @generated from field: string password = 1;
   */
  password = "";

  /**
   * @generated from field: string new_password = 2;
   */
  newPassword = "";

  constructor(data?: PartialMessage<SetWithdrawPasswordRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.SetWithdrawPasswordRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "new_password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetWithdrawPasswordRequest {
    return new SetWithdrawPasswordRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetWithdrawPasswordRequest {
    return new SetWithdrawPasswordRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetWithdrawPasswordRequest {
    return new SetWithdrawPasswordRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetWithdrawPasswordRequest | PlainMessage<SetWithdrawPasswordRequest> | undefined, b: SetWithdrawPasswordRequest | PlainMessage<SetWithdrawPasswordRequest> | undefined): boolean {
    return proto3.util.equals(SetWithdrawPasswordRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.SetWithdrawPasswordResponse
 */
export class SetWithdrawPasswordResponse extends Message<SetWithdrawPasswordResponse> {
  constructor(data?: PartialMessage<SetWithdrawPasswordResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.SetWithdrawPasswordResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetWithdrawPasswordResponse {
    return new SetWithdrawPasswordResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetWithdrawPasswordResponse {
    return new SetWithdrawPasswordResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetWithdrawPasswordResponse {
    return new SetWithdrawPasswordResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetWithdrawPasswordResponse | PlainMessage<SetWithdrawPasswordResponse> | undefined, b: SetWithdrawPasswordResponse | PlainMessage<SetWithdrawPasswordResponse> | undefined): boolean {
    return proto3.util.equals(SetWithdrawPasswordResponse, a, b);
  }
}

/**
 * Admin management messages.
 *
 * @generated from message rockgame.shop.AdminApproveWithdrawRequest
 */
export class AdminApproveWithdrawRequest extends Message<AdminApproveWithdrawRequest> {
  /**
   * @generated from field: int64 order_id = 1;
   */
  orderId = protoInt64.zero;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 admin_id = 3;
   */
  adminId = protoInt64.zero;

  constructor(data?: PartialMessage<AdminApproveWithdrawRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminApproveWithdrawRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "admin_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminApproveWithdrawRequest {
    return new AdminApproveWithdrawRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminApproveWithdrawRequest {
    return new AdminApproveWithdrawRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminApproveWithdrawRequest {
    return new AdminApproveWithdrawRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminApproveWithdrawRequest | PlainMessage<AdminApproveWithdrawRequest> | undefined, b: AdminApproveWithdrawRequest | PlainMessage<AdminApproveWithdrawRequest> | undefined): boolean {
    return proto3.util.equals(AdminApproveWithdrawRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminApproveWithdrawResponse
 */
export class AdminApproveWithdrawResponse extends Message<AdminApproveWithdrawResponse> {
  constructor(data?: PartialMessage<AdminApproveWithdrawResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminApproveWithdrawResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminApproveWithdrawResponse {
    return new AdminApproveWithdrawResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminApproveWithdrawResponse {
    return new AdminApproveWithdrawResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminApproveWithdrawResponse {
    return new AdminApproveWithdrawResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminApproveWithdrawResponse | PlainMessage<AdminApproveWithdrawResponse> | undefined, b: AdminApproveWithdrawResponse | PlainMessage<AdminApproveWithdrawResponse> | undefined): boolean {
    return proto3.util.equals(AdminApproveWithdrawResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminRejectWithdrawRequest
 */
export class AdminRejectWithdrawRequest extends Message<AdminRejectWithdrawRequest> {
  /**
   * @generated from field: int64 order_id = 1;
   */
  orderId = protoInt64.zero;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 admin_id = 3;
   */
  adminId = protoInt64.zero;

  /**
   * @generated from field: string remark = 4;
   */
  remark = "";

  constructor(data?: PartialMessage<AdminRejectWithdrawRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminRejectWithdrawRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "admin_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "remark", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRejectWithdrawRequest {
    return new AdminRejectWithdrawRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRejectWithdrawRequest {
    return new AdminRejectWithdrawRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRejectWithdrawRequest {
    return new AdminRejectWithdrawRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRejectWithdrawRequest | PlainMessage<AdminRejectWithdrawRequest> | undefined, b: AdminRejectWithdrawRequest | PlainMessage<AdminRejectWithdrawRequest> | undefined): boolean {
    return proto3.util.equals(AdminRejectWithdrawRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminRejectWithdrawResponse
 */
export class AdminRejectWithdrawResponse extends Message<AdminRejectWithdrawResponse> {
  constructor(data?: PartialMessage<AdminRejectWithdrawResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminRejectWithdrawResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRejectWithdrawResponse {
    return new AdminRejectWithdrawResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRejectWithdrawResponse {
    return new AdminRejectWithdrawResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRejectWithdrawResponse {
    return new AdminRejectWithdrawResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRejectWithdrawResponse | PlainMessage<AdminRejectWithdrawResponse> | undefined, b: AdminRejectWithdrawResponse | PlainMessage<AdminRejectWithdrawResponse> | undefined): boolean {
    return proto3.util.equals(AdminRejectWithdrawResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminMarkWithdrawPaidRequest
 */
export class AdminMarkWithdrawPaidRequest extends Message<AdminMarkWithdrawPaidRequest> {
  /**
   * @generated from field: int64 order_id = 1;
   */
  orderId = protoInt64.zero;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 admin_id = 3;
   */
  adminId = protoInt64.zero;

  constructor(data?: PartialMessage<AdminMarkWithdrawPaidRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminMarkWithdrawPaidRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "admin_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminMarkWithdrawPaidRequest {
    return new AdminMarkWithdrawPaidRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminMarkWithdrawPaidRequest {
    return new AdminMarkWithdrawPaidRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminMarkWithdrawPaidRequest {
    return new AdminMarkWithdrawPaidRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminMarkWithdrawPaidRequest | PlainMessage<AdminMarkWithdrawPaidRequest> | undefined, b: AdminMarkWithdrawPaidRequest | PlainMessage<AdminMarkWithdrawPaidRequest> | undefined): boolean {
    return proto3.util.equals(AdminMarkWithdrawPaidRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminMarkWithdrawPaidResponse
 */
export class AdminMarkWithdrawPaidResponse extends Message<AdminMarkWithdrawPaidResponse> {
  constructor(data?: PartialMessage<AdminMarkWithdrawPaidResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminMarkWithdrawPaidResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminMarkWithdrawPaidResponse {
    return new AdminMarkWithdrawPaidResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminMarkWithdrawPaidResponse {
    return new AdminMarkWithdrawPaidResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminMarkWithdrawPaidResponse {
    return new AdminMarkWithdrawPaidResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminMarkWithdrawPaidResponse | PlainMessage<AdminMarkWithdrawPaidResponse> | undefined, b: AdminMarkWithdrawPaidResponse | PlainMessage<AdminMarkWithdrawPaidResponse> | undefined): boolean {
    return proto3.util.equals(AdminMarkWithdrawPaidResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminConfirmRechargeRequest
 */
export class AdminConfirmRechargeRequest extends Message<AdminConfirmRechargeRequest> {
  /**
   * @generated from field: int64 order_id = 1;
   */
  orderId = protoInt64.zero;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 admin_id = 3;
   */
  adminId = protoInt64.zero;

  constructor(data?: PartialMessage<AdminConfirmRechargeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminConfirmRechargeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "admin_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminConfirmRechargeRequest {
    return new AdminConfirmRechargeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminConfirmRechargeRequest {
    return new AdminConfirmRechargeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminConfirmRechargeRequest {
    return new AdminConfirmRechargeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminConfirmRechargeRequest | PlainMessage<AdminConfirmRechargeRequest> | undefined, b: AdminConfirmRechargeRequest | PlainMessage<AdminConfirmRechargeRequest> | undefined): boolean {
    return proto3.util.equals(AdminConfirmRechargeRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AdminConfirmRechargeResponse
 */
export class AdminConfirmRechargeResponse extends Message<AdminConfirmRechargeResponse> {
  constructor(data?: PartialMessage<AdminConfirmRechargeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AdminConfirmRechargeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminConfirmRechargeResponse {
    return new AdminConfirmRechargeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminConfirmRechargeResponse {
    return new AdminConfirmRechargeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminConfirmRechargeResponse {
    return new AdminConfirmRechargeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminConfirmRechargeResponse | PlainMessage<AdminConfirmRechargeResponse> | undefined, b: AdminConfirmRechargeResponse | PlainMessage<AdminConfirmRechargeResponse> | undefined): boolean {
    return proto3.util.equals(AdminConfirmRechargeResponse, a, b);
  }
}

/**
 * @generated from message rockgame.shop.ClaimRechargeBonusRequest
 */
export class ClaimRechargeBonusRequest extends Message<ClaimRechargeBonusRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 order_id = 2;
   */
  orderId = protoInt64.zero;

  /**
   * @generated from field: int64 rule_id = 3;
   */
  ruleId = protoInt64.zero;

  /**
   * @generated from field: int64 bonus_amount = 4;
   */
  bonusAmount = protoInt64.zero;

  constructor(data?: PartialMessage<ClaimRechargeBonusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.ClaimRechargeBonusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "order_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "rule_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "bonus_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClaimRechargeBonusRequest {
    return new ClaimRechargeBonusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClaimRechargeBonusRequest {
    return new ClaimRechargeBonusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClaimRechargeBonusRequest {
    return new ClaimRechargeBonusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClaimRechargeBonusRequest | PlainMessage<ClaimRechargeBonusRequest> | undefined, b: ClaimRechargeBonusRequest | PlainMessage<ClaimRechargeBonusRequest> | undefined): boolean {
    return proto3.util.equals(ClaimRechargeBonusRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.ClaimRechargeBonusResponse
 */
export class ClaimRechargeBonusResponse extends Message<ClaimRechargeBonusResponse> {
  /**
   * @generated from field: bool claimed = 1;
   */
  claimed = false;

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<ClaimRechargeBonusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.ClaimRechargeBonusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "claimed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClaimRechargeBonusResponse {
    return new ClaimRechargeBonusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClaimRechargeBonusResponse {
    return new ClaimRechargeBonusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClaimRechargeBonusResponse {
    return new ClaimRechargeBonusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClaimRechargeBonusResponse | PlainMessage<ClaimRechargeBonusResponse> | undefined, b: ClaimRechargeBonusResponse | PlainMessage<ClaimRechargeBonusResponse> | undefined): boolean {
    return proto3.util.equals(ClaimRechargeBonusResponse, a, b);
  }
}

/**
 * Payment method with nested channels and bonus info.
 *
 * @generated from message rockgame.shop.PaymentMethodInfo
 */
export class PaymentMethodInfo extends Message<PaymentMethodInfo> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string icon = 3;
   */
  icon = "";

  /**
   * @generated from field: string scene = 4;
   */
  scene = "";

  /**
   * @generated from field: int64 min_amount = 5;
   */
  minAmount = protoInt64.zero;

  /**
   * @generated from field: int64 max_amount = 6;
   */
  maxAmount = protoInt64.zero;

  /**
   * @generated from field: int32 sort_order = 7;
   */
  sortOrder = 0;

  /**
   * @generated from field: repeated rockgame.shop.PaymentChannelInfo channels = 8;
   */
  channels: PaymentChannelInfo[] = [];

  /**
   * @generated from field: int32 bonus_type = 9;
   */
  bonusType = 0;

  /**
   * @generated from field: int64 bonus_value = 10;
   */
  bonusValue = protoInt64.zero;

  /**
   * @generated from field: int32 first_deposit_bonus_type = 11;
   */
  firstDepositBonusType = 0;

  /**
   * @generated from field: int64 first_deposit_bonus_value = 12;
   */
  firstDepositBonusValue = protoInt64.zero;

  constructor(data?: PartialMessage<PaymentMethodInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentMethodInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scene", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "min_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "max_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "channels", kind: "message", T: PaymentChannelInfo, repeated: true },
    { no: 9, name: "bonus_type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "bonus_value", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "first_deposit_bonus_type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "first_deposit_bonus_value", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentMethodInfo {
    return new PaymentMethodInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentMethodInfo {
    return new PaymentMethodInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentMethodInfo {
    return new PaymentMethodInfo().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentMethodInfo | PlainMessage<PaymentMethodInfo> | undefined, b: PaymentMethodInfo | PlainMessage<PaymentMethodInfo> | undefined): boolean {
    return proto3.util.equals(PaymentMethodInfo, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentChannelInfo
 */
export class PaymentChannelInfo extends Message<PaymentChannelInfo> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string method_ids = 2;
   */
  methodIds = "";

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string type = 4;
   */
  type = "";

  /**
   * @generated from field: int64 min_amount = 5;
   */
  minAmount = protoInt64.zero;

  /**
   * @generated from field: int64 max_amount = 6;
   */
  maxAmount = protoInt64.zero;

  /**
   * @generated from field: string supported_regions = 7;
   */
  supportedRegions = "";

  /**
   * @generated from field: int32 sort_order = 8;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<PaymentChannelInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentChannelInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "method_ids", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "min_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "max_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "supported_regions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentChannelInfo {
    return new PaymentChannelInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentChannelInfo {
    return new PaymentChannelInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentChannelInfo {
    return new PaymentChannelInfo().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentChannelInfo | PlainMessage<PaymentChannelInfo> | undefined, b: PaymentChannelInfo | PlainMessage<PaymentChannelInfo> | undefined): boolean {
    return proto3.util.equals(PaymentChannelInfo, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetPaymentMethodsRequest
 */
export class GetPaymentMethodsRequest extends Message<GetPaymentMethodsRequest> {
  constructor(data?: PartialMessage<GetPaymentMethodsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetPaymentMethodsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPaymentMethodsRequest {
    return new GetPaymentMethodsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPaymentMethodsRequest {
    return new GetPaymentMethodsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPaymentMethodsRequest {
    return new GetPaymentMethodsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPaymentMethodsRequest | PlainMessage<GetPaymentMethodsRequest> | undefined, b: GetPaymentMethodsRequest | PlainMessage<GetPaymentMethodsRequest> | undefined): boolean {
    return proto3.util.equals(GetPaymentMethodsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetWithdrawMethodsRequest
 */
export class GetWithdrawMethodsRequest extends Message<GetWithdrawMethodsRequest> {
  constructor(data?: PartialMessage<GetWithdrawMethodsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetWithdrawMethodsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWithdrawMethodsRequest {
    return new GetWithdrawMethodsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWithdrawMethodsRequest {
    return new GetWithdrawMethodsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWithdrawMethodsRequest {
    return new GetWithdrawMethodsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWithdrawMethodsRequest | PlainMessage<GetWithdrawMethodsRequest> | undefined, b: GetWithdrawMethodsRequest | PlainMessage<GetWithdrawMethodsRequest> | undefined): boolean {
    return proto3.util.equals(GetWithdrawMethodsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.PaymentMethodsResponse
 */
export class PaymentMethodsResponse extends Message<PaymentMethodsResponse> {
  /**
   * @generated from field: repeated rockgame.shop.PaymentMethodInfo methods = 1;
   */
  methods: PaymentMethodInfo[] = [];

  constructor(data?: PartialMessage<PaymentMethodsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.PaymentMethodsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "methods", kind: "message", T: PaymentMethodInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaymentMethodsResponse {
    return new PaymentMethodsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaymentMethodsResponse {
    return new PaymentMethodsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaymentMethodsResponse {
    return new PaymentMethodsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PaymentMethodsResponse | PlainMessage<PaymentMethodsResponse> | undefined, b: PaymentMethodsResponse | PlainMessage<PaymentMethodsResponse> | undefined): boolean {
    return proto3.util.equals(PaymentMethodsResponse, a, b);
  }
}

/**
 * Amount preset option with label filters.
 *
 * @generated from message rockgame.shop.AmountOption
 */
export class AmountOption extends Message<AmountOption> {
  /**
   * @generated from field: int64 amount = 1;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: repeated int64 include_labels = 2;
   */
  includeLabels: bigint[] = [];

  /**
   * @generated from field: repeated int64 exclude_labels = 3;
   */
  excludeLabels: bigint[] = [];

  constructor(data?: PartialMessage<AmountOption>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AmountOption";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "include_labels", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
    { no: 3, name: "exclude_labels", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AmountOption {
    return new AmountOption().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AmountOption {
    return new AmountOption().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AmountOption {
    return new AmountOption().fromJsonString(jsonString, options);
  }

  static equals(a: AmountOption | PlainMessage<AmountOption> | undefined, b: AmountOption | PlainMessage<AmountOption> | undefined): boolean {
    return proto3.util.equals(AmountOption, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetDepositAmountOptionsRequest
 */
export class GetDepositAmountOptionsRequest extends Message<GetDepositAmountOptionsRequest> {
  constructor(data?: PartialMessage<GetDepositAmountOptionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetDepositAmountOptionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDepositAmountOptionsRequest {
    return new GetDepositAmountOptionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDepositAmountOptionsRequest {
    return new GetDepositAmountOptionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDepositAmountOptionsRequest {
    return new GetDepositAmountOptionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDepositAmountOptionsRequest | PlainMessage<GetDepositAmountOptionsRequest> | undefined, b: GetDepositAmountOptionsRequest | PlainMessage<GetDepositAmountOptionsRequest> | undefined): boolean {
    return proto3.util.equals(GetDepositAmountOptionsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetWithdrawAmountOptionsRequest
 */
export class GetWithdrawAmountOptionsRequest extends Message<GetWithdrawAmountOptionsRequest> {
  constructor(data?: PartialMessage<GetWithdrawAmountOptionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetWithdrawAmountOptionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWithdrawAmountOptionsRequest {
    return new GetWithdrawAmountOptionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWithdrawAmountOptionsRequest {
    return new GetWithdrawAmountOptionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWithdrawAmountOptionsRequest {
    return new GetWithdrawAmountOptionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWithdrawAmountOptionsRequest | PlainMessage<GetWithdrawAmountOptionsRequest> | undefined, b: GetWithdrawAmountOptionsRequest | PlainMessage<GetWithdrawAmountOptionsRequest> | undefined): boolean {
    return proto3.util.equals(GetWithdrawAmountOptionsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.AmountOptionsResponse
 */
export class AmountOptionsResponse extends Message<AmountOptionsResponse> {
  /**
   * @generated from field: repeated int64 amounts = 1;
   */
  amounts: bigint[] = [];

  constructor(data?: PartialMessage<AmountOptionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.AmountOptionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amounts", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AmountOptionsResponse {
    return new AmountOptionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AmountOptionsResponse {
    return new AmountOptionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AmountOptionsResponse {
    return new AmountOptionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AmountOptionsResponse | PlainMessage<AmountOptionsResponse> | undefined, b: AmountOptionsResponse | PlainMessage<AmountOptionsResponse> | undefined): boolean {
    return proto3.util.equals(AmountOptionsResponse, a, b);
  }
}

/**
 * Shop product (deposit/withdraw amount option with bonus)
 *
 * @generated from message rockgame.shop.ShopProduct
 */
export class ShopProduct extends Message<ShopProduct> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int32 type = 2;
   */
  type = 0;

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: int64 price = 4;
   */
  price = protoInt64.zero;

  /**
   * @generated from field: int64 bonus_amount = 5;
   */
  bonusAmount = protoInt64.zero;

  /**
   * @generated from field: string currency = 6;
   */
  currency = "";

  /**
   * @generated from field: int32 sort_order = 7;
   */
  sortOrder = 0;

  constructor(data?: PartialMessage<ShopProduct>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.ShopProduct";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "price", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "bonus_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "sort_order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShopProduct {
    return new ShopProduct().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShopProduct {
    return new ShopProduct().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShopProduct {
    return new ShopProduct().fromJsonString(jsonString, options);
  }

  static equals(a: ShopProduct | PlainMessage<ShopProduct> | undefined, b: ShopProduct | PlainMessage<ShopProduct> | undefined): boolean {
    return proto3.util.equals(ShopProduct, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetDepositProductsRequest
 */
export class GetDepositProductsRequest extends Message<GetDepositProductsRequest> {
  constructor(data?: PartialMessage<GetDepositProductsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetDepositProductsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDepositProductsRequest {
    return new GetDepositProductsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDepositProductsRequest {
    return new GetDepositProductsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDepositProductsRequest {
    return new GetDepositProductsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDepositProductsRequest | PlainMessage<GetDepositProductsRequest> | undefined, b: GetDepositProductsRequest | PlainMessage<GetDepositProductsRequest> | undefined): boolean {
    return proto3.util.equals(GetDepositProductsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.GetWithdrawProductsRequest
 */
export class GetWithdrawProductsRequest extends Message<GetWithdrawProductsRequest> {
  constructor(data?: PartialMessage<GetWithdrawProductsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.GetWithdrawProductsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWithdrawProductsRequest {
    return new GetWithdrawProductsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWithdrawProductsRequest {
    return new GetWithdrawProductsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWithdrawProductsRequest {
    return new GetWithdrawProductsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWithdrawProductsRequest | PlainMessage<GetWithdrawProductsRequest> | undefined, b: GetWithdrawProductsRequest | PlainMessage<GetWithdrawProductsRequest> | undefined): boolean {
    return proto3.util.equals(GetWithdrawProductsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.shop.ShopProductsResponse
 */
export class ShopProductsResponse extends Message<ShopProductsResponse> {
  /**
   * @generated from field: repeated rockgame.shop.ShopProduct products = 1;
   */
  products: ShopProduct[] = [];

  constructor(data?: PartialMessage<ShopProductsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.shop.ShopProductsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "products", kind: "message", T: ShopProduct, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShopProductsResponse {
    return new ShopProductsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShopProductsResponse {
    return new ShopProductsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShopProductsResponse {
    return new ShopProductsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ShopProductsResponse | PlainMessage<ShopProductsResponse> | undefined, b: ShopProductsResponse | PlainMessage<ShopProductsResponse> | undefined): boolean {
    return proto3.util.equals(ShopProductsResponse, a, b);
  }
}

