// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file user.proto (package rockgame.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminItemDefineWriteRequest, AdminItemDefineWriteResponse, AdminLabelSyncRequest, AdminLabelSyncResponse, AdminMailSendRequest, AdminMailSendResponse, AdminMailTemplateWriteRequest, AdminMailTemplateWriteResponse, AdminTaskDefineWriteRequest, AdminTaskDefineWriteResponse, BatchBindLabelsRequest, BatchBindLabelsResponse, BatchUnbindLabelsRequest, BatchUnbindLabelsResponse, BindLabelRequest, BindLabelResponse, CheckVipUpgradeRequest, ClaimAttachmentRequest, ClaimAttachmentResponse, ClaimTaskRequest, ClaimTaskResponse, CreateLabelConfigRequest, CreateLabelConfigResponse, CreateTagRequest, CreateTagResponse, DailyTasksResponse, DeleteLabelConfigRequest, DeleteLabelConfigResponse, DeleteMailRequest, DeleteMailResponse, GetDailyTasksRequest, GetGrowthTasksRequest, GetInboxRequest, GetInventoryRequest, GetItemDefineListRequest, GetLabelConfigRequest, GetLabelConfigsRequest, GetLabelStatsRequest, GetTagGroupsRequest, GetTaskProgressRequest, GetUnreadCountRequest, GetUserIDsByTargetRequest, GetUserIDsByTargetResponse, GetUserLabelsRequest, GetUserTagsRequest, GetVipBenefitsRequest, GetVipInfoRequest, GetVipLevelsRequest, GetWeeklyTasksRequest, GrantItemRequest, GrantItemResponse, GrowthTasksResponse, InboxResponse, InventoryResponse, ItemDefineListResponse, LabelConfigResponse, LabelConfigsResponse, LabelStatsResponse, MatchLabelsRequest, MatchLabelsResponse, MatchTagsRequest, MatchTagsResponse, ReadMailRequest, ReadMailResponse, RefreshTagsRequest, RefreshTagsResponse, SendMailRequest, SendMailResponse, TagGroupsResponse, TaskProgressResponse, TransferItemRequest, TransferItemResponse, UnbindLabelRequest, UnbindLabelResponse, UnreadCountResponse, UpdateLabelConfigRequest, UpdateLabelConfigResponse, UseItemRequest, UseItemResponse, UserLabelsResponse, UserTagsResponse, VipBenefitsResponse, VipInfoResponse, VipLevelsResponse, VipUpgradeResponse, WeeklyTasksResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * UserService combines VIP, Item, Tag, Task, and Mail operations.
 * Implemented by user-mesh.
 *
 * @generated from service rockgame.user.UserService
 */
export const UserService = {
  typeName: "rockgame.user.UserService",
  methods: {
    /**
     * ── VIP ──
     *
     * @generated from rpc rockgame.user.UserService.GetVipLevels
     */
    getVipLevels: {
      name: "GetVipLevels",
      I: GetVipLevelsRequest,
      O: VipLevelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetVipInfo
     */
    getVipInfo: {
      name: "GetVipInfo",
      I: GetVipInfoRequest,
      O: VipInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetVipBenefits
     */
    getVipBenefits: {
      name: "GetVipBenefits",
      I: GetVipBenefitsRequest,
      O: VipBenefitsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.CheckVipUpgrade
     */
    checkVipUpgrade: {
      name: "CheckVipUpgrade",
      I: CheckVipUpgradeRequest,
      O: VipUpgradeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Item ──
     *
     * @generated from rpc rockgame.user.UserService.GetInventory
     */
    getInventory: {
      name: "GetInventory",
      I: GetInventoryRequest,
      O: InventoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetItemDefineList
     */
    getItemDefineList: {
      name: "GetItemDefineList",
      I: GetItemDefineListRequest,
      O: ItemDefineListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.UseItem
     */
    useItem: {
      name: "UseItem",
      I: UseItemRequest,
      O: UseItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.TransferItem
     */
    transferItem: {
      name: "TransferItem",
      I: TransferItemRequest,
      O: TransferItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GrantItem
     */
    grantItem: {
      name: "GrantItem",
      I: GrantItemRequest,
      O: GrantItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Tag (deprecated, use Label) ──
     *
     * @generated from rpc rockgame.user.UserService.GetUserTags
     */
    getUserTags: {
      name: "GetUserTags",
      I: GetUserTagsRequest,
      O: UserTagsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.CreateTag
     */
    createTag: {
      name: "CreateTag",
      I: CreateTagRequest,
      O: CreateTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetTagGroups
     */
    getTagGroups: {
      name: "GetTagGroups",
      I: GetTagGroupsRequest,
      O: TagGroupsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.MatchTags
     */
    matchTags: {
      name: "MatchTags",
      I: MatchTagsRequest,
      O: MatchTagsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.RefreshTags
     */
    refreshTags: {
      name: "RefreshTags",
      I: RefreshTagsRequest,
      O: RefreshTagsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Label (unified) ──
     *
     * @generated from rpc rockgame.user.UserService.GetLabelConfigs
     */
    getLabelConfigs: {
      name: "GetLabelConfigs",
      I: GetLabelConfigsRequest,
      O: LabelConfigsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetLabelConfig
     */
    getLabelConfig: {
      name: "GetLabelConfig",
      I: GetLabelConfigRequest,
      O: LabelConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.CreateLabelConfig
     */
    createLabelConfig: {
      name: "CreateLabelConfig",
      I: CreateLabelConfigRequest,
      O: CreateLabelConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.UpdateLabelConfig
     */
    updateLabelConfig: {
      name: "UpdateLabelConfig",
      I: UpdateLabelConfigRequest,
      O: UpdateLabelConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.DeleteLabelConfig
     */
    deleteLabelConfig: {
      name: "DeleteLabelConfig",
      I: DeleteLabelConfigRequest,
      O: DeleteLabelConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetUserLabels
     */
    getUserLabels: {
      name: "GetUserLabels",
      I: GetUserLabelsRequest,
      O: UserLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.BindLabel
     */
    bindLabel: {
      name: "BindLabel",
      I: BindLabelRequest,
      O: BindLabelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.UnbindLabel
     */
    unbindLabel: {
      name: "UnbindLabel",
      I: UnbindLabelRequest,
      O: UnbindLabelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.BatchBindLabels
     */
    batchBindLabels: {
      name: "BatchBindLabels",
      I: BatchBindLabelsRequest,
      O: BatchBindLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.BatchUnbindLabels
     */
    batchUnbindLabels: {
      name: "BatchUnbindLabels",
      I: BatchUnbindLabelsRequest,
      O: BatchUnbindLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.MatchLabels
     */
    matchLabels: {
      name: "MatchLabels",
      I: MatchLabelsRequest,
      O: MatchLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetLabelStats
     */
    getLabelStats: {
      name: "GetLabelStats",
      I: GetLabelStatsRequest,
      O: LabelStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Task ──
     *
     * @generated from rpc rockgame.user.UserService.GetDailyTasks
     */
    getDailyTasks: {
      name: "GetDailyTasks",
      I: GetDailyTasksRequest,
      O: DailyTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetWeeklyTasks
     */
    getWeeklyTasks: {
      name: "GetWeeklyTasks",
      I: GetWeeklyTasksRequest,
      O: WeeklyTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetGrowthTasks
     */
    getGrowthTasks: {
      name: "GetGrowthTasks",
      I: GetGrowthTasksRequest,
      O: GrowthTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetTaskProgress
     */
    getTaskProgress: {
      name: "GetTaskProgress",
      I: GetTaskProgressRequest,
      O: TaskProgressResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.ClaimTask
     */
    claimTask: {
      name: "ClaimTask",
      I: ClaimTaskRequest,
      O: ClaimTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Mail ──
     *
     * @generated from rpc rockgame.user.UserService.GetInbox
     */
    getInbox: {
      name: "GetInbox",
      I: GetInboxRequest,
      O: InboxResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.SendMail
     */
    sendMail: {
      name: "SendMail",
      I: SendMailRequest,
      O: SendMailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.ReadMail
     */
    readMail: {
      name: "ReadMail",
      I: ReadMailRequest,
      O: ReadMailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.ClaimAttachment
     */
    claimAttachment: {
      name: "ClaimAttachment",
      I: ClaimAttachmentRequest,
      O: ClaimAttachmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetUnreadCount
     */
    getUnreadCount: {
      name: "GetUnreadCount",
      I: GetUnreadCountRequest,
      O: UnreadCountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.DeleteMail
     */
    deleteMail: {
      name: "DeleteMail",
      I: DeleteMailRequest,
      O: DeleteMailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ── Admin Config CRUD ──
     *
     * @generated from rpc rockgame.user.UserService.AdminItemDefineWrite
     */
    adminItemDefineWrite: {
      name: "AdminItemDefineWrite",
      I: AdminItemDefineWriteRequest,
      O: AdminItemDefineWriteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.AdminTaskDefineWrite
     */
    adminTaskDefineWrite: {
      name: "AdminTaskDefineWrite",
      I: AdminTaskDefineWriteRequest,
      O: AdminTaskDefineWriteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.AdminMailTemplateWrite
     */
    adminMailTemplateWrite: {
      name: "AdminMailTemplateWrite",
      I: AdminMailTemplateWriteRequest,
      O: AdminMailTemplateWriteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.AdminLabelSync
     */
    adminLabelSync: {
      name: "AdminLabelSync",
      I: AdminLabelSyncRequest,
      O: AdminLabelSyncResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.AdminMailSend
     */
    adminMailSend: {
      name: "AdminMailSend",
      I: AdminMailSendRequest,
      O: AdminMailSendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rockgame.user.UserService.GetUserIDsByTarget
     */
    getUserIDsByTarget: {
      name: "GetUserIDsByTarget",
      I: GetUserIDsByTargetRequest,
      O: GetUserIDsByTargetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

