// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file vip.proto (package rockgame.vip, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddGrowthRequest, AdminCreateVIPLevelRequest, AdminCreateVIPLevelResponse, AdminDeleteVIPLevelRequest, AdminDeleteVIPLevelResponse, AdminToggleVIPLevelStatusRequest, AdminToggleVIPLevelStatusResponse, AdminUpdateVIPLevelRequest, AdminUpdateVIPLevelResponse, BenefitsResponse, CheckUpgradeRequest, GetBenefitsRequest, GrowthResponse, UpgradeResponse } from "./vip_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * VIPService is the gRPC service for VIP growth + upgrade operations.
 * Implemented by user-mesh.
 *
 * @generated from service rockgame.vip.VIPService
 */
export const VIPService = {
  typeName: "rockgame.vip.VIPService",
  methods: {
    /**
     * AddGrowth adds growth points and auto-upgrades if threshold met.
     *
     * @generated from rpc rockgame.vip.VIPService.AddGrowth
     */
    addGrowth: {
      name: "AddGrowth",
      I: AddGrowthRequest,
      O: GrowthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CheckAndUpgrade checks if the user should be upgraded.
     *
     * @generated from rpc rockgame.vip.VIPService.CheckAndUpgrade
     */
    checkAndUpgrade: {
      name: "CheckAndUpgrade",
      I: CheckUpgradeRequest,
      O: UpgradeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBenefits returns the user's current VIP benefits.
     *
     * @generated from rpc rockgame.vip.VIPService.GetBenefits
     */
    getBenefits: {
      name: "GetBenefits",
      I: GetBenefitsRequest,
      O: BenefitsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AdminCreateVIPLevel creates a new VIP level configuration.
     *
     * @generated from rpc rockgame.vip.VIPService.AdminCreateVIPLevel
     */
    adminCreateVIPLevel: {
      name: "AdminCreateVIPLevel",
      I: AdminCreateVIPLevelRequest,
      O: AdminCreateVIPLevelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AdminUpdateVIPLevel updates an existing VIP level configuration.
     *
     * @generated from rpc rockgame.vip.VIPService.AdminUpdateVIPLevel
     */
    adminUpdateVIPLevel: {
      name: "AdminUpdateVIPLevel",
      I: AdminUpdateVIPLevelRequest,
      O: AdminUpdateVIPLevelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AdminDeleteVIPLevel soft-deletes a VIP level (sets status=0).
     *
     * @generated from rpc rockgame.vip.VIPService.AdminDeleteVIPLevel
     */
    adminDeleteVIPLevel: {
      name: "AdminDeleteVIPLevel",
      I: AdminDeleteVIPLevelRequest,
      O: AdminDeleteVIPLevelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AdminToggleVIPLevelStatus toggles the active status of a VIP level.
     *
     * @generated from rpc rockgame.vip.VIPService.AdminToggleVIPLevelStatus
     */
    adminToggleVIPLevelStatus: {
      name: "AdminToggleVIPLevelStatus",
      I: AdminToggleVIPLevelStatusRequest,
      O: AdminToggleVIPLevelStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

