// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file vip.proto (package rockgame.vip, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.vip.AddGrowthRequest
 */
export class AddGrowthRequest extends Message<AddGrowthRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * "recharge", "task", "admin_adjust"
   *
   * @generated from field: string source = 3;
   */
  source = "";

  constructor(data?: PartialMessage<AddGrowthRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AddGrowthRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddGrowthRequest {
    return new AddGrowthRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddGrowthRequest {
    return new AddGrowthRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddGrowthRequest {
    return new AddGrowthRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddGrowthRequest | PlainMessage<AddGrowthRequest> | undefined, b: AddGrowthRequest | PlainMessage<AddGrowthRequest> | undefined): boolean {
    return proto3.util.equals(AddGrowthRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.GrowthResponse
 */
export class GrowthResponse extends Message<GrowthResponse> {
  /**
   * @generated from field: int32 old_level = 1;
   */
  oldLevel = 0;

  /**
   * @generated from field: int32 new_level = 2;
   */
  newLevel = 0;

  /**
   * @generated from field: bool upgraded = 3;
   */
  upgraded = false;

  /**
   * @generated from field: int64 total_growth = 4;
   */
  totalGrowth = protoInt64.zero;

  constructor(data?: PartialMessage<GrowthResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.GrowthResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "old_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "new_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "upgraded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "total_growth", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrowthResponse {
    return new GrowthResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrowthResponse {
    return new GrowthResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrowthResponse {
    return new GrowthResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GrowthResponse | PlainMessage<GrowthResponse> | undefined, b: GrowthResponse | PlainMessage<GrowthResponse> | undefined): boolean {
    return proto3.util.equals(GrowthResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.CheckUpgradeRequest
 */
export class CheckUpgradeRequest extends Message<CheckUpgradeRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  constructor(data?: PartialMessage<CheckUpgradeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.CheckUpgradeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CheckUpgradeRequest {
    return new CheckUpgradeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CheckUpgradeRequest {
    return new CheckUpgradeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CheckUpgradeRequest {
    return new CheckUpgradeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CheckUpgradeRequest | PlainMessage<CheckUpgradeRequest> | undefined, b: CheckUpgradeRequest | PlainMessage<CheckUpgradeRequest> | undefined): boolean {
    return proto3.util.equals(CheckUpgradeRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.UpgradeResponse
 */
export class UpgradeResponse extends Message<UpgradeResponse> {
  /**
   * @generated from field: bool upgraded = 1;
   */
  upgraded = false;

  /**
   * @generated from field: int32 old_level = 2;
   */
  oldLevel = 0;

  /**
   * @generated from field: int32 new_level = 3;
   */
  newLevel = 0;

  constructor(data?: PartialMessage<UpgradeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.UpgradeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "upgraded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "old_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "new_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpgradeResponse {
    return new UpgradeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpgradeResponse {
    return new UpgradeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpgradeResponse {
    return new UpgradeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpgradeResponse | PlainMessage<UpgradeResponse> | undefined, b: UpgradeResponse | PlainMessage<UpgradeResponse> | undefined): boolean {
    return proto3.util.equals(UpgradeResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.GetBenefitsRequest
 */
export class GetBenefitsRequest extends Message<GetBenefitsRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  constructor(data?: PartialMessage<GetBenefitsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.GetBenefitsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBenefitsRequest {
    return new GetBenefitsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBenefitsRequest {
    return new GetBenefitsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBenefitsRequest {
    return new GetBenefitsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBenefitsRequest | PlainMessage<GetBenefitsRequest> | undefined, b: GetBenefitsRequest | PlainMessage<GetBenefitsRequest> | undefined): boolean {
    return proto3.util.equals(GetBenefitsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.BenefitsResponse
 */
export class BenefitsResponse extends Message<BenefitsResponse> {
  /**
   * @generated from field: int32 level = 1;
   */
  level = 0;

  /**
   * @generated from field: string level_name = 2;
   */
  levelName = "";

  /**
   * @generated from field: repeated string benefits = 3;
   */
  benefits: string[] = [];

  /**
   * VIP daily signin bonus amount
   *
   * @generated from field: int64 daily_signin_bonus = 4;
   */
  dailySigninBonus = protoInt64.zero;

  /**
   * VIP withdraw fee rate (×10000 basis points)
   *
   * @generated from field: int64 withdraw_fee_rate = 5;
   */
  withdrawFeeRate = protoInt64.zero;

  /**
   * VIP daily withdraw limit (×1000 scale)
   *
   * @generated from field: int64 max_withdraw_daily = 6;
   */
  maxWithdrawDaily = protoInt64.zero;

  constructor(data?: PartialMessage<BenefitsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.BenefitsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "level_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "benefits", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "daily_signin_bonus", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "withdraw_fee_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "max_withdraw_daily", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BenefitsResponse {
    return new BenefitsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BenefitsResponse {
    return new BenefitsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BenefitsResponse {
    return new BenefitsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BenefitsResponse | PlainMessage<BenefitsResponse> | undefined, b: BenefitsResponse | PlainMessage<BenefitsResponse> | undefined): boolean {
    return proto3.util.equals(BenefitsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminCreateVIPLevelRequest
 */
export class AdminCreateVIPLevelRequest extends Message<AdminCreateVIPLevelRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: int64 growth_required = 2;
   */
  growthRequired = protoInt64.zero;

  /**
   * @generated from field: int64 withdraw_fee_rate = 3;
   */
  withdrawFeeRate = protoInt64.zero;

  /**
   * @generated from field: int64 daily_signin_bonus = 4;
   */
  dailySigninBonus = protoInt64.zero;

  /**
   * @generated from field: int32 status = 5;
   */
  status = 0;

  constructor(data?: PartialMessage<AdminCreateVIPLevelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminCreateVIPLevelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "growth_required", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "withdraw_fee_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "daily_signin_bonus", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateVIPLevelRequest {
    return new AdminCreateVIPLevelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateVIPLevelRequest {
    return new AdminCreateVIPLevelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateVIPLevelRequest {
    return new AdminCreateVIPLevelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateVIPLevelRequest | PlainMessage<AdminCreateVIPLevelRequest> | undefined, b: AdminCreateVIPLevelRequest | PlainMessage<AdminCreateVIPLevelRequest> | undefined): boolean {
    return proto3.util.equals(AdminCreateVIPLevelRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminCreateVIPLevelResponse
 */
export class AdminCreateVIPLevelResponse extends Message<AdminCreateVIPLevelResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<AdminCreateVIPLevelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminCreateVIPLevelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateVIPLevelResponse {
    return new AdminCreateVIPLevelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateVIPLevelResponse {
    return new AdminCreateVIPLevelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateVIPLevelResponse {
    return new AdminCreateVIPLevelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateVIPLevelResponse | PlainMessage<AdminCreateVIPLevelResponse> | undefined, b: AdminCreateVIPLevelResponse | PlainMessage<AdminCreateVIPLevelResponse> | undefined): boolean {
    return proto3.util.equals(AdminCreateVIPLevelResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminUpdateVIPLevelRequest
 */
export class AdminUpdateVIPLevelRequest extends Message<AdminUpdateVIPLevelRequest> {
  /**
   * @generated from field: int64 level_id = 1;
   */
  levelId = protoInt64.zero;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional int64 growth_required = 3;
   */
  growthRequired?: bigint;

  /**
   * @generated from field: optional int64 withdraw_fee_rate = 4;
   */
  withdrawFeeRate?: bigint;

  /**
   * @generated from field: optional int64 daily_signin_bonus = 5;
   */
  dailySigninBonus?: bigint;

  /**
   * @generated from field: optional int32 status = 6;
   */
  status?: number;

  constructor(data?: PartialMessage<AdminUpdateVIPLevelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminUpdateVIPLevelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "growth_required", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 4, name: "withdraw_fee_rate", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 5, name: "daily_signin_bonus", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 6, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateVIPLevelRequest {
    return new AdminUpdateVIPLevelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateVIPLevelRequest {
    return new AdminUpdateVIPLevelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateVIPLevelRequest {
    return new AdminUpdateVIPLevelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateVIPLevelRequest | PlainMessage<AdminUpdateVIPLevelRequest> | undefined, b: AdminUpdateVIPLevelRequest | PlainMessage<AdminUpdateVIPLevelRequest> | undefined): boolean {
    return proto3.util.equals(AdminUpdateVIPLevelRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminUpdateVIPLevelResponse
 */
export class AdminUpdateVIPLevelResponse extends Message<AdminUpdateVIPLevelResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<AdminUpdateVIPLevelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminUpdateVIPLevelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateVIPLevelResponse {
    return new AdminUpdateVIPLevelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateVIPLevelResponse {
    return new AdminUpdateVIPLevelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateVIPLevelResponse {
    return new AdminUpdateVIPLevelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateVIPLevelResponse | PlainMessage<AdminUpdateVIPLevelResponse> | undefined, b: AdminUpdateVIPLevelResponse | PlainMessage<AdminUpdateVIPLevelResponse> | undefined): boolean {
    return proto3.util.equals(AdminUpdateVIPLevelResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminDeleteVIPLevelRequest
 */
export class AdminDeleteVIPLevelRequest extends Message<AdminDeleteVIPLevelRequest> {
  /**
   * @generated from field: int64 level_id = 1;
   */
  levelId = protoInt64.zero;

  constructor(data?: PartialMessage<AdminDeleteVIPLevelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminDeleteVIPLevelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDeleteVIPLevelRequest {
    return new AdminDeleteVIPLevelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDeleteVIPLevelRequest {
    return new AdminDeleteVIPLevelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDeleteVIPLevelRequest {
    return new AdminDeleteVIPLevelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDeleteVIPLevelRequest | PlainMessage<AdminDeleteVIPLevelRequest> | undefined, b: AdminDeleteVIPLevelRequest | PlainMessage<AdminDeleteVIPLevelRequest> | undefined): boolean {
    return proto3.util.equals(AdminDeleteVIPLevelRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminDeleteVIPLevelResponse
 */
export class AdminDeleteVIPLevelResponse extends Message<AdminDeleteVIPLevelResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 2;
   */
  deleted = false;

  constructor(data?: PartialMessage<AdminDeleteVIPLevelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminDeleteVIPLevelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDeleteVIPLevelResponse {
    return new AdminDeleteVIPLevelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDeleteVIPLevelResponse {
    return new AdminDeleteVIPLevelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDeleteVIPLevelResponse {
    return new AdminDeleteVIPLevelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDeleteVIPLevelResponse | PlainMessage<AdminDeleteVIPLevelResponse> | undefined, b: AdminDeleteVIPLevelResponse | PlainMessage<AdminDeleteVIPLevelResponse> | undefined): boolean {
    return proto3.util.equals(AdminDeleteVIPLevelResponse, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminToggleVIPLevelStatusRequest
 */
export class AdminToggleVIPLevelStatusRequest extends Message<AdminToggleVIPLevelStatusRequest> {
  /**
   * @generated from field: int64 level_id = 1;
   */
  levelId = protoInt64.zero;

  constructor(data?: PartialMessage<AdminToggleVIPLevelStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminToggleVIPLevelStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminToggleVIPLevelStatusRequest {
    return new AdminToggleVIPLevelStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminToggleVIPLevelStatusRequest {
    return new AdminToggleVIPLevelStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminToggleVIPLevelStatusRequest {
    return new AdminToggleVIPLevelStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminToggleVIPLevelStatusRequest | PlainMessage<AdminToggleVIPLevelStatusRequest> | undefined, b: AdminToggleVIPLevelStatusRequest | PlainMessage<AdminToggleVIPLevelStatusRequest> | undefined): boolean {
    return proto3.util.equals(AdminToggleVIPLevelStatusRequest, a, b);
  }
}

/**
 * @generated from message rockgame.vip.AdminToggleVIPLevelStatusResponse
 */
export class AdminToggleVIPLevelStatusResponse extends Message<AdminToggleVIPLevelStatusResponse> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: int32 status = 2;
   */
  status = 0;

  constructor(data?: PartialMessage<AdminToggleVIPLevelStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.vip.AdminToggleVIPLevelStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminToggleVIPLevelStatusResponse {
    return new AdminToggleVIPLevelStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminToggleVIPLevelStatusResponse {
    return new AdminToggleVIPLevelStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminToggleVIPLevelStatusResponse {
    return new AdminToggleVIPLevelStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminToggleVIPLevelStatusResponse | PlainMessage<AdminToggleVIPLevelStatusResponse> | undefined, b: AdminToggleVIPLevelStatusResponse | PlainMessage<AdminToggleVIPLevelStatusResponse> | undefined): boolean {
    return proto3.util.equals(AdminToggleVIPLevelStatusResponse, a, b);
  }
}

