// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file wallet.proto (package rockgame.wallet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BalanceResponse, GetBalanceRequest, GetTotalBalancesRequest, TotalBalancesResponse, UpdateAssetsRequest, UpdateAssetsResponse } from "./wallet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * WalletService is the gRPC service for all money operations.
 * Implemented by wallet-node.
 *
 * @generated from service rockgame.wallet.WalletService
 */
export const WalletService = {
  typeName: "rockgame.wallet.WalletService",
  methods: {
    /**
     * UpdateAssets is the unified interface for all asset operations.
     * act field determines the operation type (recharge/withdraw/bet/settle/cancel/settle_pot/credit_bonus).
     *
     * @generated from rpc rockgame.wallet.WalletService.UpdateAssets
     */
    updateAssets: {
      name: "UpdateAssets",
      I: UpdateAssetsRequest,
      O: UpdateAssetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBalance returns the user's current wallet balances + statistics.
     *
     * @generated from rpc rockgame.wallet.WalletService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: GetBalanceRequest,
      O: BalanceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTotalBalances returns aggregate sums across ALL wallet shards.
     * Used by admin dashboard for platform-wide stats (total player balance,
     * GGR, etc.). Replaces cross-shard ShardedUnionAllRaw SQL queries that
     * would otherwise bypass the wallet-node abstraction.
     *
     * @generated from rpc rockgame.wallet.WalletService.GetTotalBalances
     */
    getTotalBalances: {
      name: "GetTotalBalances",
      I: GetTotalBalancesRequest,
      O: TotalBalancesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

