// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file wallet.proto (package rockgame.wallet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message rockgame.wallet.UpdateAssetsRequest
 */
export class UpdateAssetsRequest extends Message<UpdateAssetsRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  /**
   * @generated from field: string tx_id = 2;
   */
  txId = "";

  /**
   * ActRecharge/ActWithdraw/ActBet/ActSettle/ActCancel/ActSettlePot/ActCreditBonus
   *
   * @generated from field: string act = 3;
   */
  act = "";

  /**
   * primary amount (paise)
   *
   * @generated from field: int64 amount = 4;
   */
  amount = protoInt64.zero;

  /**
   * for settle: original bet
   *
   * @generated from field: int64 bet_amount = 5;
   */
  betAmount = protoInt64.zero;

  /**
   * for settle: win
   *
   * @generated from field: int64 win_amount = 6;
   */
  winAmount = protoInt64.zero;

  /**
   * @generated from field: string game_id = 7;
   */
  gameId = "";

  /**
   * @generated from field: string round_id = 8;
   */
  roundId = "";

  /**
   * @generated from field: string bet_tx_id = 9;
   */
  betTxId = "";

  /**
   * @generated from field: string biz_type = 10;
   */
  bizType = "";

  /**
   * @generated from field: string biz_id = 11;
   */
  bizId = "";

  /**
   * @generated from field: string remark = 12;
   */
  remark = "";

  /**
   * @generated from field: string source = 13;
   */
  source = "";

  /**
   * settle: amount to add to total_valid_flow (0 = skip)
   *
   * @generated from field: int64 valid_flow_amount = 14;
   */
  validFlowAmount = protoInt64.zero;

  /**
   * credit_bonus: increase withdraw_limit
   *
   * @generated from field: int64 withdraw_limit_increase = 15;
   */
  withdrawLimitIncrease = protoInt64.zero;

  constructor(data?: PartialMessage<UpdateAssetsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.UpdateAssetsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "act", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "bet_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "win_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "game_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "round_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "bet_tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "biz_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "biz_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "remark", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "valid_flow_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 15, name: "withdraw_limit_increase", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAssetsRequest {
    return new UpdateAssetsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAssetsRequest {
    return new UpdateAssetsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAssetsRequest {
    return new UpdateAssetsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAssetsRequest | PlainMessage<UpdateAssetsRequest> | undefined, b: UpdateAssetsRequest | PlainMessage<UpdateAssetsRequest> | undefined): boolean {
    return proto3.util.equals(UpdateAssetsRequest, a, b);
  }
}

/**
 * @generated from message rockgame.wallet.UpdateAssetsResponse
 */
export class UpdateAssetsResponse extends Message<UpdateAssetsResponse> {
  /**
   * @generated from field: int64 cash_balance = 1;
   */
  cashBalance = protoInt64.zero;

  /**
   * @generated from field: int64 bonus_balance = 2;
   */
  bonusBalance = protoInt64.zero;

  /**
   * @generated from field: int64 frozen_balance = 3;
   */
  frozenBalance = protoInt64.zero;

  /**
   * @generated from field: int64 total_balance = 4;
   */
  totalBalance = protoInt64.zero;

  /**
   * @generated from field: int64 total_recharge = 5;
   */
  totalRecharge = protoInt64.zero;

  /**
   * @generated from field: int64 total_withdraw = 6;
   */
  totalWithdraw = protoInt64.zero;

  /**
   * @generated from field: int64 total_bet = 7;
   */
  totalBet = protoInt64.zero;

  /**
   * @generated from field: int64 total_win = 8;
   */
  totalWin = protoInt64.zero;

  /**
   * @generated from field: int64 total_valid_flow = 9;
   */
  totalValidFlow = protoInt64.zero;

  /**
   * @generated from field: int64 withdraw_limit = 10;
   */
  withdrawLimit = protoInt64.zero;

  /**
   * @generated from field: int32 recharge_count = 11;
   */
  rechargeCount = 0;

  /**
   * @generated from field: int32 withdraw_count = 12;
   */
  withdrawCount = 0;

  /**
   * @generated from field: string tx_id = 13;
   */
  txId = "";

  /**
   * @generated from field: bool dup = 14;
   */
  dup = false;

  /**
   * @generated from field: int64 win_amount = 15;
   */
  winAmount = protoInt64.zero;

  constructor(data?: PartialMessage<UpdateAssetsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.UpdateAssetsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cash_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "bonus_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "frozen_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "total_recharge", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "total_withdraw", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "total_bet", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "total_win", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "total_valid_flow", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "withdraw_limit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "recharge_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "withdraw_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "dup", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "win_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAssetsResponse {
    return new UpdateAssetsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAssetsResponse {
    return new UpdateAssetsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAssetsResponse {
    return new UpdateAssetsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAssetsResponse | PlainMessage<UpdateAssetsResponse> | undefined, b: UpdateAssetsResponse | PlainMessage<UpdateAssetsResponse> | undefined): boolean {
    return proto3.util.equals(UpdateAssetsResponse, a, b);
  }
}

/**
 * @generated from message rockgame.wallet.GetBalanceRequest
 */
export class GetBalanceRequest extends Message<GetBalanceRequest> {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId = protoInt64.zero;

  constructor(data?: PartialMessage<GetBalanceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.GetBalanceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined, b: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined): boolean {
    return proto3.util.equals(GetBalanceRequest, a, b);
  }
}

/**
 * @generated from message rockgame.wallet.BalanceResponse
 */
export class BalanceResponse extends Message<BalanceResponse> {
  /**
   * @generated from field: int64 cash_balance = 1;
   */
  cashBalance = protoInt64.zero;

  /**
   * @generated from field: int64 bonus_balance = 2;
   */
  bonusBalance = protoInt64.zero;

  /**
   * @generated from field: int64 frozen_balance = 3;
   */
  frozenBalance = protoInt64.zero;

  /**
   * @generated from field: int64 total_balance = 4;
   */
  totalBalance = protoInt64.zero;

  /**
   * @generated from field: int64 total_recharge = 5;
   */
  totalRecharge = protoInt64.zero;

  /**
   * @generated from field: int64 total_withdraw = 6;
   */
  totalWithdraw = protoInt64.zero;

  /**
   * @generated from field: int64 total_bet = 7;
   */
  totalBet = protoInt64.zero;

  /**
   * @generated from field: int64 total_win = 8;
   */
  totalWin = protoInt64.zero;

  /**
   * @generated from field: int64 total_valid_flow = 9;
   */
  totalValidFlow = protoInt64.zero;

  /**
   * @generated from field: int64 withdraw_limit = 10;
   */
  withdrawLimit = protoInt64.zero;

  /**
   * @generated from field: int32 recharge_count = 11;
   */
  rechargeCount = 0;

  /**
   * @generated from field: int32 withdraw_count = 12;
   */
  withdrawCount = 0;

  constructor(data?: PartialMessage<BalanceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.BalanceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cash_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "bonus_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "frozen_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "total_recharge", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "total_withdraw", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "total_bet", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "total_win", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "total_valid_flow", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "withdraw_limit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "recharge_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "withdraw_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BalanceResponse {
    return new BalanceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BalanceResponse {
    return new BalanceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BalanceResponse {
    return new BalanceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BalanceResponse | PlainMessage<BalanceResponse> | undefined, b: BalanceResponse | PlainMessage<BalanceResponse> | undefined): boolean {
    return proto3.util.equals(BalanceResponse, a, b);
  }
}

/**
 * Reserved for future filters (e.g. by registration date, VIP level).
 * Currently returns sums across all wallets.
 *
 * @generated from message rockgame.wallet.GetTotalBalancesRequest
 */
export class GetTotalBalancesRequest extends Message<GetTotalBalancesRequest> {
  constructor(data?: PartialMessage<GetTotalBalancesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.GetTotalBalancesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTotalBalancesRequest {
    return new GetTotalBalancesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTotalBalancesRequest {
    return new GetTotalBalancesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTotalBalancesRequest {
    return new GetTotalBalancesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTotalBalancesRequest | PlainMessage<GetTotalBalancesRequest> | undefined, b: GetTotalBalancesRequest | PlainMessage<GetTotalBalancesRequest> | undefined): boolean {
    return proto3.util.equals(GetTotalBalancesRequest, a, b);
  }
}

/**
 * @generated from message rockgame.wallet.TotalBalancesResponse
 */
export class TotalBalancesResponse extends Message<TotalBalancesResponse> {
  /**
   * SUM(cash_balance)
   *
   * @generated from field: int64 total_cash_balance = 1;
   */
  totalCashBalance = protoInt64.zero;

  /**
   * SUM(bonus_balance)
   *
   * @generated from field: int64 total_bonus_balance = 2;
   */
  totalBonusBalance = protoInt64.zero;

  /**
   * SUM(frozen_balance)
   *
   * @generated from field: int64 total_frozen_balance = 3;
   */
  totalFrozenBalance = protoInt64.zero;

  /**
   * SUM(total_recharge)
   *
   * @generated from field: int64 total_recharge = 4;
   */
  totalRecharge = protoInt64.zero;

  /**
   * SUM(total_withdraw)
   *
   * @generated from field: int64 total_withdraw = 5;
   */
  totalWithdraw = protoInt64.zero;

  /**
   * SUM(total_bet)
   *
   * @generated from field: int64 total_bet = 6;
   */
  totalBet = protoInt64.zero;

  /**
   * SUM(total_win)
   *
   * @generated from field: int64 total_win = 7;
   */
  totalWin = protoInt64.zero;

  /**
   * SUM(total_valid_flow)
   *
   * @generated from field: int64 total_valid_flow = 8;
   */
  totalValidFlow = protoInt64.zero;

  /**
   * COUNT(*) — number of wallet rows
   *
   * @generated from field: int64 wallet_count = 9;
   */
  walletCount = protoInt64.zero;

  constructor(data?: PartialMessage<TotalBalancesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rockgame.wallet.TotalBalancesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_cash_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "total_bonus_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "total_frozen_balance", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_recharge", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "total_withdraw", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "total_bet", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "total_win", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "total_valid_flow", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "wallet_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TotalBalancesResponse {
    return new TotalBalancesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TotalBalancesResponse {
    return new TotalBalancesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TotalBalancesResponse {
    return new TotalBalancesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: TotalBalancesResponse | PlainMessage<TotalBalancesResponse> | undefined, b: TotalBalancesResponse | PlainMessage<TotalBalancesResponse> | undefined): boolean {
    return proto3.util.equals(TotalBalancesResponse, a, b);
  }
}

